### ISSUE TITLE
`chunked` parameter in query method doesn't work

### ISSUE THREAD

**Issue by pkaeding** [influxdata/influxdb-python#21]
It seems that this library will just try to parse as json the full string, once it all comes down, which:
- defeats the purpose of streaming the chunks
- won't work, since there will be many JSON objects in the stream

I'm not sure that this is really possible using [requests](https://github.com/kennethreitz/requests/issues/2020) without jumping through some crazy hoops.

**Comment by CBarraford** [comment]
I opened a PR that is relating to this ticket. When pulling down chunked response its nice for the server side as it utilizes less memory, but client side you'd have to store it all in memory which wouldn't work if you're querying for GBs of data. This [PR](https://github.com/influxdb/influxdb-python/pull/126) allows you to stream directly to disk.
