### ISSUE TITLE
How to get tags from ResponseSet?

### ISSUE THREAD

**Issue by nemesisdesign** [influxdata/influxdb-python#214]
How to get tag values from `ResponseSet` objects? Is it possible at all?

**Comment by aviau** [comment]
See the API documentation [here](http://influxdb-python.readthedocs.org/en/latest/api-documentation.html#influxdb.resultset.ResultSet.keys)

Keys are tuples (serie_name, tags)

**Comment by nemesisdesign** [comment]
Hi @aviau, I meant to say, is it possible to get a list of points in which the values contain tags too?

Fed

**Comment by aviau** [comment]
>  in which the values contain tags 

Hmm? Sorry I don't quite understand. Values are not tags.

If tag sets are different. There will be different series.

One thing I plan to do is include tags in poinst. So that you can do rs.get_points() and still get tags.

**Comment by nemesisdesign** [comment]
Yes that would be great, especially if the order of the points would be ordered by time.
I assumed points with different tags are not ordered by time because I tried to do `get_points()`on a measurements with different tags and display the results on a linear graph and I got a picasso painting :-).

**Comment by xginn8** [comment]
ResultSets now return tags as well when calling `get_points()`, closing.

**Comment by samaust** [comment]
> 
> 
> ResultSets now return tags as well when calling `get_points()`, closing.

It seems that: 

- get_points() does not return tags
- items() returns tags

**Comment by biqqles** [comment]
@samaust is still correct (which makes sense since the last release on PyPI was just before his comment). This issue should be reopened.

For other people coming up against this, here is my workaround:

```Python
# we /should/ be able to pass get_points() straight to DataFrame, but contrary to the docs this doesn't
# include tags at the moment. So let's roll our own implementation
query_result = client.query(query).items()
frame = pandas.DataFrame({**tags, **next(fields)} for (measurement_name, tags), fields in query_result)
```

Hope this helps.

**Comment by rajvijay68** [comment]
I got the tags this way

```python
results = influx_client.query(query)

for row in results.items(): 
      tag_value = row[0][1]["tag_name"]
      data = list(row[1])
```
