### ISSUE TITLE
InfluxDBClient: Access to connection parameters

### ISSUE THREAD

**Issue by dstreppa** [influxdata/influxdb-python#241]
The most of connection parameters (ex: host, port, etc.) are declared private. Instead some others (`use_udp` and `use_port`) are public (see below):

`self._verify_ssl = verify_ssl`

`self.use_udp = use_udp`
`self.udp_port = udp_port`
`self._session = requests.Session()`

Why this difference?

**Comment by gst** [comment]
bad consistency I'd say; there is effectively a way to enhance / correct that.

**Comment by aviau** [comment]
> bad consistency I'd say

Yep, there was no specific reason.

**Comment by babilen** [comment]
Would you prefer `host`, `port`, .. to be public or for `use_udp` and `use_port` to be private?

**Comment by dstreppa** [comment]
I would say `host` and `port` to be public

**Comment by aviau** [comment]
I don't really mind. However moving use_udp to private could break some usage of the lib.

**Comment by sebito91** [comment]
Moved both UDP params to private on #477, this is covered in test cases at the moment.

We should mention this in the new release to ensure smooth transition. If anything, we can add a property for the next release to help, but leave it to you @aviau to decide. Happy to improve where necessary
