### ISSUE TITLE
Certificate issue with Ubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by cmiller8** [influxdata/influxdb-python#247]
I have been using `influxdb-python` quite a bit on my Mac OSX machine with success in interfacing with an InfluxDB 0.9.1 server hosted by InfluxDB. They require ssl and thus I have been setting up the client with ssl:

```
 client = InfluxDBClient(host, port, login, pw, ssl=True, verify_ssl=False)
```

However, when I tried to spin up an AWS Ubuntu 12.04 instance and use the same Python code, my writes were never successful -- however there was never an error.

I eventually trouble-shooted by using `curl` from the shell and got the following error:

```
curl: (77) error setting certificate verify locations:
CAfile: /etc/pki/tls/certs/ca-bundle.crt
CApath: none
```

I used the guidance [here](https://github.com/JuliaLang/BinDeps.jl/issues/122) to let the shell know where the proper CA file path is.

For Python, I eventually figured out to get `pycurl`to work by using the following code:

```
import pycurl
import certifi
apiURL = 'https://'+host+':'+port+'/write?u='+login+'&p='+pw+'&db=particletest'
c = pycurl.Curl()
c.setopt(c.URL, apiURL)
poststring = measurementname+',sensorbank='+device+',type='+sensortype+' value='+str(value)+' '+str(timestamp) 
c.setopt(c.POSTFIELDS, poststring)
c.setopt(pycurl.CAINFO, certifi.where())
c.perform()
```

But, still can't get `influxdb-python` to work in this OS

**Comment by sebito91** [comment]
@cmiller8 is this still an issue? Sorry for the massively delayed response! :face_with_head_bandage:

**Comment by xginn8** [comment]
closing due to lack of response
