### ISSUE TITLE
How to set time using SeriesHelper?

### ISSUE THREAD

**Issue by JernejJerin** [influxdata/influxdb-python#259]
I tried to use SeriesHelper to set the time, but it keeps getting overridden with default current time when saving into DB. I have added it to the fields (don't know if this is correct, as the documentation does not specify anything about setting time):

```
class MeteorologicalDataHelper(SeriesHelper):
    # Meta class stores time series helper configuration.
    class Meta:
        # The client should be an instance of InfluxDBClient.
        client = myclient
        # The series name must be a string. Add dependent fields/tags in curly brackets.
        series_name = 'meteorological_data'
        # Defines all the fields in this time series.
        fields = ['time', 'air_temperature']
        # Defines all the tags for the series.
        tags = []
        # Defines the number of data points to store prior to writing on the wire.
        bulk_size = 100
        # autocommit must be set to True when using bulk_size
        autocommit = True
```

But it seems that this value is not used, for example I have executed the following:
`MeteorologicalDataHelper(air_temperature=12, time=1434067467000000000)`

And then checked in console of influx and the time was set to current time instead of the provided one:
```
> select * from meteorological_data
name: meteorological_data
-------------------------
time				air_temperature
2015-10-25T13:05:06.736935489Z 	12
```

**Comment by simisimis** [comment]
I have this problem as well... And I am new to programming, so difficult to figure, but maybe it has something to do that in normal write_points call time is outside fields dict:
```
    json_body = [
        {
            "measurement": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64
            }
        }
    ]
```

**Comment by JernejJerin** [comment]
A quick fix. Just add the following to the helper.py in the `_json_body_` method (after the initialization of `json_point`):
```
if 'time' in cls._fields:
    json_point['time'] = point.__dict__['time']
```
But you do need to have attribute `time` specified in the fields.

**Comment by gst** [comment]
```
    json_point['time'] = point.__dict__['time']
```

just, why not `point['time']` ?

**Comment by gst** [comment]
> just, why not point['time'] ?

I meant `point.time` ..

**Comment by memic** [comment]
hi, when is this issue marked as fixed?
