### ISSUE TITLE
Timeout issue

### ISSUE THREAD

**Issue by ajijohn** [influxdata/influxdb-python#263]
raise InfluxDBServerError(response.content)
influxdb.exceptions.InfluxDBServerError: timeout

I'm doing a large set of inserts, one measurement a sec, it timeout after 4 hrs

**Comment by gst** [comment]
If you wish someone to help you then please provide more details :)

1) step(s) to reproduce the issue (as clear as possible)
2) what were your expecting vs what you got
3) the versions of the components you have: python version, influxdb-server version, and for sure this package version ;)

**Comment by ajijohn** [comment]
Apologies for being vague.  I'm using InfluxDB v0.9.4 , Python version 2.7.6 on mac, and using influxdb-python . I'm not sure how to replicate it by providing a script. What I've is a json with close to quarter million time-series data points, and for each datapoint I call client.write_points(...) . 

I am writing to a server hosted on azure, and it was failing repeatedly with aforesaid error.  I was using dns name of the influx db server , and thought the issue might be with dns-query , and switched to IP , and the issue disappeared. Not sure, if my theory is well founded.

**Comment by gst** [comment]
Hi @ajijohn ,

When you used dns name instead of IP to contact your server :
do you get an error/exception from influxdb-python ? please provide it fully then, with the full stacktrace if available (should be). Cause as it is (without any error/exception detail provided) I'm not certain that it's related to influxdb-python actually.. (It might have been a "simple" temporary error with your dns system..)

you fullfilled my questions up to ~50% only (0 & 3 are more or less clearly answered but not 1 & 2) ;)

> and for each datapoint I call client.write_points(...) .

.. and what happened by then ? In each of the 2 cases where you use the IP to contact the server and where you use its host/servername and what did you got and what did you expected ?

**Comment by oricou** [comment]
Same problem, I have a loop which puts hundreds of Pandas Dataframe in InfluxDB. It works and at one time:

```
Traceback (most recent call last):
  File "influx15.py", line 24, in <module>
    client.write_points(df, sym, time_precision='s')
  File "/usr/local/lib/python2.7/dist-packages/influxdb/_dataframe_client.py", line 68, in write_points
    points, time_precision, database, retention_policy)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 373, in write_points
    tags=tags)
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 418, in _write_points
    expected_response_code=204
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 260, in write
    headers=headers
  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 226, in request
    raise InfluxDBServerError(response.content)
influxdb.exceptions.InfluxDBServerError: timeout
```

According to my log file it seems the Python loop send hundreds of thousands (more than 1/2 million) http request like:

```
[http] 2016/01/02 15:49:47 127.0.0.1 - root [02/Jan/2016:15:49:47 +0100] POST /write?db=bourse2&precision=s HTTP/1.1 204 0 - python-requests/2.9.1 11772f27-b160-11e5-8d7d-000000000000 73.81725ms
```

and at the end of the log file I see few

```
[wal] 2016/01/02 16:24:14 Flush due to idle. Flushing 286 series with 286 points and 17786 bytes from partition 1
[wal] 2016/01/02 16:24:14 write to index of partition 1 took 56.907979ms
```

Could it be that InfluxDB buffer has exploded? Python sending the data without waiting for InfluxDB?

Olivier.

**Comment by aviau** [comment]
Timeout exceptions can happen. It could be that InfluxDB was busy or that you had network issues. If you write millions of points, you should catch those exceptions and react accordingly.

Unless you think influxdb-python was at fault here, I'll close this issue. Feel free to poke me back if you have more info.
