### ISSUE TITLE
SeriesHelper inserting only last point from the set

### ISSUE THREAD

**Issue by simisimis** [influxdata/influxdb-python#264]
I am using influxdb 0.9.4.2
and this example to submit multiple points to database
http://influxdb-python.readthedocs.org/en/latest/examples.html#tutorials-serieshelper

I am trying to post 35 points per query.
I don't know if it's just me, but whenever I run my script it adds to db only last point.
If I set bulk_size=1 and in python script insert time.sleep(1) after every MySeriesHelper() call
then I am able to post most of the points(32-35).

**Comment by aviau** [comment]
When inserting points with the same timestamp, influxdb only keeps the last.

**Comment by aviau** [comment]
For this reason, #130 will be important

**Comment by felixduvallet** [comment]
I have also come across this very unexpected "feature". It's hard to see how the SeriesHelper feature was meant to be used; even the tutorial only inserts the last point (unless bulk_size=1).

Any thoughts on updating the documentation at least until #130 is resolved?
