### ISSUE TITLE
Non string/int types are treated as boolean

### ISSUE THREAD

**Issue by andybelltree** [influxdata/influxdb-python#269]
Because of a bug in my code, I was accidentally writing dictionaries as values for a few fields, and the error message I was getting was misleading.

> myclient.write_points([{'measurement':'faketable','tags':{'x': True},'fields':{'y': 13,'my_list_col':[1,2,3]}}])

will return

> influxdb.exceptions.InfluxDBClientError: 400: unable to parse 'faketable,x=True my_list_col=[1, 2, 3],y=13i': invalid boolean

InfluxDB line protocol assumes that anything that isn't in quotes, numeric or numeric followed by an 'i' is a boolean, so this error message is actually saying it couldn't process the list that I passed.

Would it be helpful to either reject unsupported types or automatically put them in quotes and send them as string representations?

Nb. This only applies to fields, not tags. Inserting a list or dictionary as a tag value works fine.

**Comment by sebito91** [comment]
This should be addressed in recent PRs. If this is not the case please let me know and we can reopen!
