### ISSUE TITLE
Allow for configuring a JSON serializer

### ISSUE THREAD

**Issue by hynek** [influxdata/influxdb-python#272]
Right now I’m trying to import 11 GB of data and the ETA is 20h. :)  I’ve noticed, that you use the standard library’s JSON encoder which is the slowest of them all (except on PyPy).

Could you add an option to the client to set an own `dumps` method so I can use something faster as simplejson, ujson, or RapidJSON?  A real life example for that can be found e.g. in [Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/1.5-branch/api/renderers.html#pyramid.renderers.JSON).

**Comment by aviau** [comment]
@hynek  I wouldn't be against this. Do you want to open a pull request implementing it?

**Comment by hynek** [comment]
ISTM that I’ve overestimated the actual usage of JSON within the driver (at least my later research indicated that).  As we’ve decided against using InfluxDB I’ll not have the time to get involved and wouldn’t have any hard feelings if you’d close this.  Unless I’ve missed something and JSON serialization *is* a big part.

**Comment by sebito91** [comment]
Closing stale issue.
