### ISSUE TITLE
data frame with tag columns

### ISSUE THREAD

**Issue by mingzhou** [influxdata/influxdb-python#286]
I would like to insert the following pandas data frame into influx.

| [index] | tag1 | tag2 | field1 | field2|
| --- | --- | --- | ---| --- | --- |
| 2016-01-01 | "MSFT" | "NYSE" | 1.1 | 2.2 | 
| 2016-01-01 | "AAPL" | "NYSE" | 3.3 | 4.4 |

` [index]` is the index of the data frame.
`tag1` and `tag2` are influx tags.
`field1` and `field2` are influx fields.

How could I do this by using `DataFrameClient`? Thanks.

**Comment by aviau** [comment]
@tzonghao Has been supporting the DataFrame Client up until now. He may be able to answer your question.

**Comment by tzonghao** [comment]
@mingzhou `DataFrameClient.write_points` accepts `tags` as keyword argument. The data frame argument should only contain time series data. For your case, you could either construct separate data frame objects upfront for each distinct tag combinations, or use `pandas.DataFrame.groupby` to separate them out by tag combinations, and then call `write_points` for each data frame. For example, to separate and write such data frame with many tag combinations to influxdb:

```python
grouped = df.groupby(['tag1', 'tag2'])
for group in grouped.groups:
    tag1, tag2 = group
    tags = dict(tag1=tag1, tag2=tag2)
    sub_df = df.get_group(group)[[field1, field2]]
    dfclient.write_points(sub_df, measurement, tags=tags)
```

**Comment by aviau** [comment]
Thank you @tzonghao .

I'll close the issue for now, unless @mingzhou has more questions.

**Comment by gte620v** [comment]
There is a `tag_columns` argument in the `DataFrameClient.write_points` now.  See https://github.com/influxdata/influxdb-python/pull/364

**Comment by laimaretto** [comment]
Hi! I've tried the suggestion here but I'm having trouble with the index. This is my data.
```
t = time.strftime('%Y-%m-%d %H:%M:%S')
headers = ['index','tag1','tag2','field1','field2']
data 	= [[t,'MSFT','NYSE',1.1,2.2],[t,'APPL','NYSE',3.3,4.4]]
```

If I try to insert the complete DF at once using the `DataFrameClient`, I would do:
```
timeValues 	= df[ ['index','field1','field2'] ]
tags 		= { 't1': df[['tag1']], 't2': df[['tag2']]  }
dbConnDF = DataFrameClient('127.0.0.1', 8086, 'root', 'root', 'pnmNG')
dbConnDF.write_points(timeValues, 'test', tags = tags)
```
This does not work. I get the following error:
```
Traceback (most recent call last):
  File "testPD.py", line 29, in <module>
    dbConnDF.write_points(timeValues, 'test', tags = tags)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/_dataframe_client.py", line 117, in write_points
    numeric_precision=numeric_precision)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/_dataframe_client.py", line 240, in _convert_dataframe_to_lines
    PeriodIndex.')
TypeError: Must be DataFrame with DatetimeIndex or PeriodIndex.
```
However, if I for-loop over **the same data**, and insert the same information into influx, row by row, I can accomplish that using `InfluxDBClient` without any error.

```
t 	= time.strftime('%Y-%m-%d %H:%M:%S')
headers = ['index','tag1','tag2','field1','field2']
data 	= [[t,'MSFT','NYSE',1.1,2.2],[t,'APPL','NYSE',3.3,4.4]]
for row in data:
  bodyDB = [{"measurement":'test', "tags":{"tag1": row[1],"tag2": row[2]},"time": row[0],"fields":{"field1":row[3],"field2":row[4]}}]
  dbConnQRY.write_points(bodyDB)
```
What is it that I'm missing to fully use the `DataFrameClient`? Any hints?

Thanks!

**Comment by gte620v** [comment]
The `tags` argument expects a list of tag column names, not a dict of the tags.

**Comment by laimaretto** [comment]
Hi. I've read here[1] and here[2] that the `tags` argument is indeed a dictionary of tags.

Nevertheless, I tried your suggestion: I replaced the dict of tags with a list of tag column names. It does not work either ...

```
timeValues 	= df[ ['time','field1','field2'] ]
tags 		= ['tag1','tag2']	
dbConnDF = DataFrameClient('127.0.0.1', 8086, 'root', 'root', 'pnmNG')
dbConnDF.write_points(timeValues, 'test', tags = tags)
```
Here's the error ...
```
Traceback (most recent call last):
  File "testPD.py", line 26, in <module>
    dbConnDF.write_points(timeValues, 'test', tags = tags)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/_dataframe_client.py", line 117, in write_points
    numeric_precision=numeric_precision)
  File "/usr/local/lib/python3.5/dist-packages/influxdb/_dataframe_client.py", line 240, in _convert_dataframe_to_lines
    PeriodIndex.')
TypeError: Must be DataFrame with DatetimeIndex or PeriodIndex.
```
As per the error, it seems to me that the DFClient can't find the proper index of the data frame to be inserted into influx ...

thanks!

[1] - https://github.com/influxdata/influxdb-python/blob/master/influxdb/_dataframe_client.py#L44
[2] - https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_pandas.py#L31

**Comment by gte620v** [comment]
Sorry, I didn't look at the error closely before.  Your problem is that the index is not a datetime index.

You need to do some combination of `pd.to_datetime` and `df.set_index` to get your dataframe to have a datetimeindex.  You seem to have a column of string called `index`, which is not the same thing.  You need convert these strings to datetime objects with `pd.to_datetime` and then pass that column to `df.set_index`.

See https://stackoverflow.com/questions/27032052/how-do-i-properly-set-the-datetimeindex-for-a-pandas-datetime-object-in-a-datafr

**Comment by laimaretto** [comment]
You're right! Thanks for the tip. I had to both convert to datetime and also set the index.

```
t = time.strftime('%Y-%m-%d %H:%M:%S')
headers = ['time','tag1','tag2','field1','field2']
data 	= [[t,'MSFT','NYSE',1.3,2.5],[t,'APPL','NYSE',3.5,4.24]]
df 		= pd.DataFrame(data, columns = headers)
df['time'] = pd.to_datetime(df['time'])
df 		= df.set_index('time')
dbConnDF.write_points(df, 'test', tags = tags)
```
Now it's inserting all the data nicely ...
```
> select * from test
name: test
time                field1 field2 tag1 tag2
----                ------ ------ ---- ----
1506866720000000000 3.5    4.24   APPL NYSE
1506866720000000000 1.3    2.5    MSFT NYSE
1506866773000000000 3.5    4.24   APPL NYSE
1506866773000000000 1.3    2.5    MSFT NYSE
> 
> show tag keys from test
name: test
tagKey
------
tag1
tag2
> 
> show field keys from test
name: test
fieldKey fieldType
-------- ---------
field1   float
field2   float
```
Thanks!

**Comment by rounak9791** [comment]
when i try the below snippet 
t = time.strftime('%Y-%m-%d %H:%M:%S')
    headers = ['time', 'tag1', 'tag2', 'field1', 'field2']
    data = [[t, 'MSFT', 'NYSE', 1.3, 2.5], [t, 'APPL', 'NYSE', 3.5, 4.24]]
    df = pd.DataFrame(data, columns=headers)
    df['time'] = pd.to_datetime(df['time'])
    df = df.set_index('time')
    tags = {'tag1': df[['tag1']], 'tag2': df[['tag2']]}
    client.write_points(df, 'test', tags=tags)

i get the error:
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all()

**Comment by rounak9791** [comment]
Also it wish to insert values with similar timestamps..
df index allows it but when i use write_points in the db i see only unique values of the timestamp entries

**Comment by ethanlinys** [comment]
<img width="929" alt="case" src="https://user-images.githubusercontent.com/18170680/36433932-b80fe5b4-1698-11e8-88a7-56d40f54acc1.png">
Any one can help me with this problem?

**Comment by mousumipaul** [comment]
when I tried @laimaretto  code above in python 3.6.4 i got the following error.
"TypeError: write_points() got multiple values for argument 'time_precision'".
I have checked the index of the dataframe is datetime but i failed to execute it. Please help me to overcome this issue.
