### ISSUE TITLE
Writes broken with influx 0.10.0?

### ISSUE THREAD

**Issue by BGraco** [influxdata/influxdb-python#293]
I am wondering if anyone else else has has success using the current python client with the latest influx? I am using an older version of the code, but I have had no issues up until now and looking at the diffs I don't see anything that would help.

Queries work fine for me 

The first write appears to work, then I get lots of connection errors.

connectionpool.py, requests.packages.urllib3.connectionpool,"Resetting dropped connection: localhost"
connectionpool.py, requests.packages.urllib3.connectionpool,"Starting new HTTP connection (2): localhost"
connectionpool.py, requests.packages.urllib3.connectionpool,"Starting new HTTP connection (3): localhost"
connectionpool.py, requests.packages.urllib3.connectionpool,"Starting new HTTP connection (4): localhost"

I can CURL the writes with no issues, so I don't think this is an influxdb issue, but  I am unsure what could have changed to break the client.

**Comment by adventures91** [comment]
I am also getting these errors with the latest release of the python client and influx 0.10. I also can no longer create users or databases with the client. I can curl or use the influx CLI to perform these actions without issue. So it seems that there must have been breaking changes tot he client in influxdb 0.10.

**Comment by BGraco** [comment]
Write are not broken, but the new influx seems to kill the client connection quite often, which was causing other issues in the application.
