### ISSUE TITLE
Searching for first/last time values

### ISSUE THREAD

**Issue by deeplook** [influxdata/influxdb-python#297]
I don't see a way to define and execute a query that returns the first and last timestamp for which there is some data? I know there are the functions `first(:fieldname)` and `last(:fieldname)`, but these will return the data values and not their respective timestamps. But I want to determine the _time span_ during which a device produced some data.

**Comment by aviau** [comment]
This issue has nothing to do with the python library, please open an issue for InfluxDB instead.
