### ISSUE TITLE
UDP Client Example

### ISSUE THREAD

**Issue by csulmone** [influxdata/influxdb-python#299]
No example code exists for using UDP functionality in the influxdb-python client.  Additionally, the documentation is sparse as to what is contained in the packet to be written.

**Comment by rdrey** [comment]
There is one example here: http://influxdb-python.readthedocs.org/en/latest/api-documentation.html

```
# using UDP
client = InfluxDBClient(host='127.0.0.1', database='dbname', use_udp=True, udp_port=4444)
```

But it is a little tough to find and could easily be repeated in the main readme as well.

**Comment by aviau** [comment]
Usage of the client does not change if you are using UDP. What else could be documented? Closing unless you have suggestions. Feel free to comment again.
