### ISSUE TITLE
Specify Retention Policy in SeriesHelper 

### ISSUE THREAD

**Issue by matt-snider** [influxdata/influxdb-python#300]
It would be good to be able to specify the Retention Policy on a per `SeriesHelper` basis.

At the moment I'm employing a straight-forward hack:

``` python
class MySeriesHelper(SeriesHelper):
     class Meta:
        # ....

     @classmethod
     def commit(cls, client=None):
        # Overwrite this method to add the retention policy. This is a temp
        # hack until this can be applied to upstream.
        if not client:
            client = cls._client
        rtn = client.write_points(cls._json_body_(), retention_policy='my_retention_policy')
        cls._reset_()
        return rtn
```

I'm not sure if I'm missing something and there is actually a better way to do this. But if not, I think it can be fairly easily implemented by adding a new parameter to `Meta`.

I'd be interested in working on this if you think it's a worthwhile feature.

**Comment by sebito91** [comment]
Addressed in #723
