### ISSUE TITLE
Why all fields must be present in SeriesHelper?

### ISSUE THREAD

**Issue by codeb2cc** [influxdata/influxdb-python#302]
```
class SeriesHelper(object):
    def __init__(self, **kw):                                                 
        """
        Constructor call creates a new data point. All fields must be present.
        """
```

Why _SeriesHelper_ has such constraint? Fields in InfluxDB are not indexed. Data points can be spatial in fields to ignore some missing values.

**Comment by spott** [comment]
This should be doable by creating a default value of None in the internal representation, and then, in `_json_body_` checking for that default representation and not passing the field if it contains it.

Or am I missing some subtlety here...
