### ISSUE TITLE
Travis Build - Could not find influxd binary

### ISSUE THREAD

**Issue by matt-snider** [influxdata/influxdb-python#305]
Hi @aviau!

I ran the test suite locally on master and a few of the server tests failed:
   * ERROR: test_write_points_udp (influxdb.tests.server_tests.client_test_with_server.UdpTests)
   * FAIL: test_create_user_blank_username (influxdb.tests.server_tests.client_test_with_server.SimpleTests)
   * FAIL: test_create_user_invalid_username (influxdb.tests.server_tests.client_test_with_server.SimpleTests)

So I went and looked at the travis builds and noticed that the last build where these tests weren't skipped was [here](https://travis-ci.org/influxdata/influxdb-python/jobs/105673629), just before updating the travis build to use influxdb 0.9.6.1. Maybe it's something as simple as a changed file path in the new version.

**Comment by aviau** [comment]
InfluxDB is no longer in /opt by default I think. But find_influxd_path should still find it: https://github.com/influxdata/influxdb-python/blob/master/influxdb/tests/server_tests/influxdb_instance.py#L151

**Comment by aviau** [comment]
Closed in 0d05ca40710d4183cc6b8056a6089dbaa0509963
