### ISSUE TITLE
ResultSet.get_points: tags keyword does not work

### ISSUE THREAD

**Issue by phoenixyz** [influxdata/influxdb-python#307]
Hi,

I am using influxdb-python 2.12.0 from pip with InfluxDB 0.10.3.

With the following ResultSet:

    ResultSet({'('memory_value', None)': [{'time': '2016-03-17T15:54:38.897247Z', 'value': 721354752.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:39.133806Z', 'value': 698204160.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:39.89737Z', 'value': 721350656.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:40.133975Z', 'value': 698228736.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:40.897071Z', 'value': 721375232.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:41.133549Z', 'value': 698245120.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:41.897153Z', 'value': 721334272.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:42.133719Z', 'value': 698236928.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:42.89731Z', 'value': 721330176.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:43.133955Z', 'value': 698224640.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:43.897524Z', 'value': 721551360.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:44.133511Z', 'value': 698413056.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}]})

When I use result.get_points("memory_value") I get

    [{'time': '2016-03-17T15:54:38.897247Z', 'value': 721354752.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:39.133806Z', 'value': 698204160.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:39.89737Z', 'value': 721350656.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:40.133975Z', 'value': 698228736.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:40.897071Z', 'value': 721375232.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:41.133549Z', 'value': 698245120.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:41.897153Z', 'value': 721334272.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:42.133719Z', 'value': 698236928.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:42.89731Z', 'value': 721330176.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:43.133955Z', 'value': 698224640.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}, {'time': '2016-03-17T15:54:43.897524Z', 'value': 721551360.0, 'type_instance': 'used', 'host': '192.168.0.114', 'type': 'memory'}, {'time': '2016-03-17T15:54:44.133511Z', 'value': 698413056.0, 'type_instance': 'used', 'host': '192.168.0.115', 'type': 'memory'}]

as expected.
When I use result.get_points("memory_value", tags={"host": "192.168.0.114"}) I get

    []

Is that expected behaviour and I am doing it wrong or is this a bug?

**Comment by aviau** [comment]
Hmm... It looks like "host" is a field in your example?

It should be a tag. You can't filter by field values.

**Comment by aviau** [comment]
I'll close this. But feel free to ask questions if you don't understand my comment.
