### ISSUE TITLE
Change InfluxDBClient `verify_ssl` default to True

### ISSUE THREAD

**Issue by caitlin615** [influxdata/influxdb-python#311]
Since the default behavior for a request in the requests library is to set `verify=True`, can the InfluxDBClient `verify_ssl` default be changed to mirror that of the requests defaults? Currently it's set to `False`, and using HTTPS (with a CA-signed cert) produces `InsecureRequestWarning`. The default behavior should be to follow the defaults of the request library to verify SSL. Should someone need to disable verification, they should be set explicitly when creating a new client (if you're using self-signed certs, for example). The choice to make the default False seems backwards.

Is there a reason the default is `verify_ssl=False` and can it be changed to `verify_ssl=True`?

**Comment by aviau** [comment]
I wouldn't think most users have SSL enabled on their InfluxDB instances.

Also, this would break the API.

**Comment by aviau** [comment]
For the reason above, I am closing this issue.

It is simple to configure, so I see no good reason to break the API for 30k users.

**Comment by Arvanaghi** [comment]
@aviau What's the best way to get the InfluxDB client to trust a self-signed certificate?

**Comment by julien10** [comment]
I got it to work by specifying : `verify_ssl="path_to_your_cert"` when initialising the InfluxDBClient.

**Comment by colindean** [comment]
I was _very_ surprised by having to opt into security by adding `verify_ssl=True` when I encountered this warning message in my logs:

```
opt/venv/lib/python3.7/site-packages/urllib3/connectionpool.py:988: InsecureRequestWarning: Unverified HTTPS request is being made to host 'influxdb.example.test'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
```

I at first thought that my CA bundle that includes some self-signed CA stuff was incorrectly configured, but alas, no: this influxdb client is not verifying certificates by default. The underlying functionality in `requests` recommends [only disabling verification for testing purposes](https://docs.python-requests.org/en/latest/api/#requests.Session.verify).

@julien10 Your suggestion isn't working how you think it is. That ends up evaluating truthy: the path to the cert isn't actually used, it seems, once passed to `requests`.
