### ISSUE TITLE
InfluxDBClient.get_list_series() was broken by InfluxDB v0.11.0 API change

### ISSUE THREAD

**Issue by Tomcat-Engineering** [influxdata/influxdb-python#314]
The `InfluxDBClient.get_list_series()` method runs the "SHOW SERIES" query, but InfluxDB's response to that query has [completely changed in v0.11.0](https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v0110-2016-03-22) so the client can't parse the response.

**Comment by babilen** [comment]
This causes the `test_get_list_series_and_delete` to fail and, obviously, requires changes to `get_list_series`. 

In particular data is now being returned in line format (cf. https://docs.influxdata.com/influxdb/latest/write_protocols/line/) and needs to be parsed.

**Comment by mindlessbrain** [comment]
Any updates on this issue, guys?

**Comment by sebito91** [comment]
Closing stale issue, please let me know if still required and we can re-open to investigate.
