### ISSUE TITLE
Chunked http requests

### ISSUE THREAD

**Issue by ozansener** [influxdata/influxdb-python#318]
I am a little bit puzzled with this feature. I need to query very large time-series and if I do not use chunked queries, my influxdb server is having problems. Is there any problem to re-include chunked queries?.

**Comment by aviau** [comment]
Please foward this to github.com/influxdata/influxdb

**Comment by kostko** [comment]
The new 1.2.0 behaviour is to require chunked responses for returning responses longer than 10,000 points (without changing `max-row-limit`). But for some reason the Python client doesn't even support chunking?

I see that there is a chunked JSON parser in the repository and that the `query` method even supported chunking in the past, but this was removed with commit d1b8edf6c864b6da93f56b3b54d29d9479e8d601 for some reason?
