### ISSUE TITLE
travis tests have been failing for a while

### ISSUE THREAD

**Issue by aisch** [influxdata/influxdb-python#323]
seems since ~ https://travis-ci.org/influxdata/influxdb-python/builds/116902069

**Comment by aviau** [comment]
We should fix this ASAP before merging new things.

**Comment by babilen** [comment]
@aviau A lot of these tests seem to fail as points are now unicode strings rather than str. A possible fix would be to adapt the tests to it or to figure out what introduced that change.

What would you see as the preferred approach?

**Comment by aviau** [comment]
Adapting the tests is fine as long as they show that the library works ;)

**Comment by babilen** [comment]
Well, I am not a huge fan of simply adapting the test suite so that the tests pass. Something must have triggered the type change and in some tests types seem to be inconsistent.

See, for example, the following:

```
======================================================================
FAIL: test_get_list_series_and_delete (influxdb.tests.server_tests.client_test_with_server.CommonTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/babilen/src/github.com/influxdb/influxdb-python/influxdb/tests/server_tests/client_test_with_server.py", line 480, in test_get_list_series_and_delete
    rsp
AssertionError: Lists differ: [{u'name': u'cpu_load_short', ... != [{'name': 'results', 'tags': [...

First differing element 0:
{'name': 'cpu_load_short', 'tags': [{'_key': 'cpu_load_short,host=server01,region=us-west', u'region': u'us-west', u'host': u'server01'}]}
{'name': 'results', 'tags': [{u'key': u'cpu_load_short,host=server01,region=us-west'}]}
```

where we see a mixture of `unicode` and `str`.

**Comment by aviau** [comment]
We should return unicode to the user everywhere if that is possible.

**Comment by babilen** [comment]
Do you have an idea why points and tags behave that way, while `'name': 'results', 'tags'` in there do not?

**Comment by aviau** [comment]
We probably create those keys in result_set.py.

**Comment by babilen** [comment]
Most problems stem from the upgrade to InfluxDB 0.12.1 and the resulting changes in 103c7dc85607b3bb157af4cca4972c006bae7780

**Comment by babilen** [comment]
Updating to `0.13.0` lets `test_issue_143` pass again due to https://github.com/influxdata/influxdb/pull/6283

**Comment by aviau** [comment]
Thanks to @babilen, the test suite was fixed!
