### ISSUE TITLE
Bulk in SeriesHelper from example not working as expected

### ISSUE THREAD

**Issue by Speedy1991** [influxdata/influxdb-python#324]
Expected n=bulk_size entries in influxdb, but only the last one is persistent

In your example it is:
```python
MySeriesHelper(server_name='us.east-1', some_stat=155, other_stat=50)
```
I think a timestamp have to be passed to the the SeriesHelper-json

**Comment by aviau** [comment]
see #306

As of this PR:
```
If time is not specified the implementation defaults to using datetime.utcnow(). This occurs at point-creation, not within the call to _json_body_(). 
```

This will prevent an issue where sending multiple points with the same time squashes them.

**Comment by Speedy1991** [comment]
ok thanks, but if i run your example there is still only 1 entry in influxdb. Does that mean i have to add the time field into the Metaclass to make the example working corectly?

**Comment by aviau** [comment]
PR #306 is not available in a release yet
