### ISSUE TITLE
Please provide  influxdb.__version__

### ISSUE THREAD

**Issue by babilen** [influxdata/influxdb-python#325]
Hi all,

the API of this library seems to change rather frequently and it would help tremendously if there would be an easy way to check for different library versions. I kindly ask you to provide `influxdb.__version__` for this in the future.

Thank you!

**Comment by aviau** [comment]
https://github.com/influxdata/influxdb-python/blob/master/influxdb/__init__.py

**Comment by aviau** [comment]
We already provide it. Let me know if you meant something else.

**Comment by babilen** [comment]
No, that's exactly what I meant! Wonderful .. when was that introduced? Wonder why I didn't spot it?

**Comment by babilen** [comment]
Ah, ever since 0.1.0 (cf. 9bae5a4a9fa89676c939df9028fbc8383b620330)

Thank you!
