### ISSUE TITLE
write() issues

### ISSUE THREAD

**Issue by dantespe** [influxdata/influxdb-python#326]
Can someone give me a basic example of how to format the dictionary `data`?

**Comment by aviau** [comment]
Look at the README or at the docs: https://influxdb-python.readthedocs.io/en/latest/

**Comment by dantespe** [comment]
There is no example in the README!

**Comment by aviau** [comment]
Oh.

Are you sure you don't mean to use write_points?

**Comment by dantespe** [comment]
The function that: 'writes data to InfluxDB is `write(data, params=None, expected_response_code=204)`

My only question was how to I format the `data` dictionary. 

Would it look like: `data : { 'measurement,tag=A': value#}`?

**Comment by aviau** [comment]
If you want to write points, use write_points.
