### ISSUE TITLE
ImportError: cannot import name InfluxDBClient

### ISSUE THREAD

**Issue by dantespe** [influxdata/influxdb-python#327]
Is anyone else having trouble using the influxdb module? My code was working then suddenly python no longer recognized the InfluxDBClient object.

**Comment by rainiera** [comment]
What kind of error are you getting? If it's an `ImportError: No module named influxdb`, it's likely that influxdb isn't in your site-packages and you're using a different python installation than the one you did `pip install influxdb` on. See if `influxdb` is one of the folders by running this command in the terminal: `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())" | xargs ls`.

**Comment by kevincheng96** [comment]
I have this issue as well. What was the fix? My issue was:
ImportError: cannot import name InfluxDBClient

**Comment by inselbuch** [comment]
if you have a file that happens to match a standard .py module, you can get this error... for example, do not create a file called

selectors.py

**Comment by monikamulani** [comment]
I'm getting this error:
ImportError: cannot import name DataFrameClient

following does work
from influxdb import InfluxDBClient

Please help

**Comment by VJPranay** [comment]
from influxdb import InfluxDBClient
ImportError: cannot import name 'InfluxDBClient' from 'influxdb'

same error

**Comment by xginn8** [comment]
Hi @VJPranay can you provide a little more information about your set up? Do you have a file called `influxdb.py` in your path or project somewhere?

**Comment by onefourfive** [comment]
Hi I'm having this issue as well.

OS: Ubuntu 20.04 on Windows Subsystem for Linux
Running python3 in terminal within empty folder

pip output:
```
pip3 install --upgrade influxdb
Requirement already up-to-date: influxdb in ./.local/lib/python3.8/site-packages (5.3.1)
Requirement already satisfied, skipping upgrade: msgpack in ./.local/lib/python3.8/site-packages (from influxdb) (1.0.0)
Requirement already satisfied, skipping upgrade: pytz in ./.local/lib/python3.8/site-packages (from influxdb) (2020.4)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.0 in ./.local/lib/python3.8/site-packages (from influxdb) (2.8.1)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from influxdb) (1.14.0)
Requirement already satisfied, skipping upgrade: requests>=2.17.0 in /usr/lib/python3/dist-packages (from influxdb) (2.22.0)
```

Console output:
```
~$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from influxdb import InfluxDbClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'InfluxDbClient' from 'influxdb' (/home/user/.local/lib/python3.8/site-packages/influxdb/__init__.py)
```

**Comment by onefourfive** [comment]
> 
> 
> Hi I'm having this issue as well.
> 
> OS: Ubuntu 20.04 on Windows Subsystem for Linux
> Running python3 in terminal within empty folder
> 
> pip output:
> 
> ```
> pip3 install --upgrade influxdb
> Requirement already up-to-date: influxdb in ./.local/lib/python3.8/site-packages (5.3.1)
> Requirement already satisfied, skipping upgrade: msgpack in ./.local/lib/python3.8/site-packages (from influxdb) (1.0.0)
> Requirement already satisfied, skipping upgrade: pytz in ./.local/lib/python3.8/site-packages (from influxdb) (2020.4)
> Requirement already satisfied, skipping upgrade: python-dateutil>=2.6.0 in ./.local/lib/python3.8/site-packages (from influxdb) (2.8.1)
> Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3/dist-packages (from influxdb) (1.14.0)
> Requirement already satisfied, skipping upgrade: requests>=2.17.0 in /usr/lib/python3/dist-packages (from influxdb) (2.22.0)
> ```
> 
> Console output:
> 
> ```
> ~$ python3
> Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from influxdb import InfluxDbClient
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'InfluxDbClient' from 'influxdb' (/home/user/.local/lib/python3.8/site-packages/influxdb/__init__.py)
> ```

PEBKAC: Caps issue, `InfluxDbClient` should be `InfluxDBClient`.
