### ISSUE TITLE
Queries NOT SELECT and SHOW should be posts

### ISSUE THREAD

**Issue by wx00** [influxdata/influxdb-python#329]
Since v0.13, queries sent to the database `/query` endpoints that are not `SELECT` or `SHOW` should be using `POST` rather than `GET`, and v1.0.0 is now in beta, this should be fixed recently.

Ref: 

[Deprecated `/query` endpoint request behavior](https://docs.influxdata.com/influxdb/v0.13/administration/012_vs_013/#deprecated-query-endpoint-request-behavior)

[query `GET` in source code](https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L329)

**Comment by aviau** [comment]
I don't have much time to work on this right now, but I am able to review and merge if someone wants to do the work.

**Comment by sebito91** [comment]
Closing stale issue, please reopen if this is still required.
