### ISSUE TITLE
Timestamps slightly different in Influxdb

### ISSUE THREAD

**Issue by hirochri** [influxdata/influxdb-python#344]
Occasionally my data arrives in the database with timestamps that are ever so slightly ahead or behind the time they actually should be, and I have been having trouble tracking down where this behavior is coming from!

I am using a pandas dataframe with a datetime index, which is being written to the database using [write_points](https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L352) (No specified time precision). The timestamps within the dataframe are numpy datetime64[ns]'s and Influx's default time precision is also nanoseconds iirc. What often happens though is that the timestamps in the database are slightly different and looks like it possibly has to do with floats? (My problem is similar to [this](https://groups.google.com/forum/#!topic/influxdb/uyp1kmMXwxI), as queries based on time now miss 1 or 2 data points)

For instance, this is how the following timestamps change:

datetime64[ns]                              -->         unix timestamp in Influxdb
2016-06-20 13:35:42.270000       -->        1466429742270000128
2016-06-20 14:02:49.770000       -->        1466431369769999872

If anyone could clarify why this behavior is happening or point me in the right direction of how to fix it, that would be greatly appreciated, thanks!

Edit: After glancing at the other possible issues, it may very well be related to [Issue 340](https://github.com/influxdata/influxdb-python/issues/340)

**Comment by inselbuch** [comment]
this is still a problem... it is simply not possible to reliably overwrite data by specifying the exact same timestamp

**Comment by nargiza-sarkulova** [comment]
I also experienced this problem. I'm very much interested in answer.
