### ISSUE TITLE
is this twisted safe?

### ISSUE THREAD

**Issue by cad** [influxdata/influxdb-python#348]
Is this library can be used properly with twisted the async python networking library?

**Comment by aviau** [comment]
I don't know. What are the requirements for that?

**Comment by cad** [comment]
@aviau the requirements  would be not making any blocking i/o calls IMAHO.

**Comment by aviau** [comment]
Then it is incompatible with the way we use requests?

**Comment by whalecalls** [comment]
@cad you can use twisted fine with this library. handle the blocking calls the same you you any other blocking call, in a seperate thread other then reactor. plrease reference 
http://twistedmatrix.com/documents/13.2.0/core/howto/threading.html

**Comment by DanielOneM** [comment]
@cad alternatively there's this: https://github.com/vasco-santos/Twisted_InfluxDB_Driver

**Comment by cad** [comment]
Then for twisted style of doing things see @DanielOneM's answer above.  If you are going to handle blocking calls yourself see @whalecalls's answer. Thanks.

Closing this.
