### ISSUE TITLE
HELP timestamp  Error 204

### ISSUE THREAD

**Issue by markwinap** [influxdata/influxdb-python#372]
Help please :( error 204 when i insert the date time ( error 204)
# !/usr/bin/python

from influxdb import InfluxDBClient
from apscheduler.schedulers.blocking import BlockingScheduler
import threading
import requests
import pypyodbc
import logging
from datetime import timedelta
from datetime import datetime, date, time

logging.basicConfig()

def pull_data():
    ls = []
    c = 0
    connection = pypyodbc.connect("DRIVER={SQL Server};SERVER=10.101.162.240;UID=user_test;PWD=Admin123;DATABASE=tcs_awdb")
    cursor = connection.cursor() 
    SQLCommand = ("SELECT Termination_Call_Detail.CallTypeID, Termination_Call_Detail.RouteID, Count = SUM(CASE WHEN Termination_Call_Detail.CallDispositionFlag = 1 THEN 1 ELSE 0 END), Duration = SUM(Duration), RingTime = SUM(RingTime), HoldTime = SUM(HoldTime), TalkTime = SUM(TalkTime), QueueTime = SUM(Duration - (RingTime + HoldTime + TalkTime)) FROM Termination_Call_Detail WHERE DateTime between DATEADD(minute,-6,GETDATE()) and DATEADD(minute,-1,GETDATE()) AND RouteID IS NOT NULL GROUP BY Termination_Call_Detail.CallTypeID, Termination_Call_Detail.RouteID")
    cursor.execute(SQLCommand)
    results = cursor.fetchone()
    while results:
        ls.append({"measurement": "handled","tags": {"type": "current", "calltypeid": results[0],"routeid": results[1]},"time": datetime.utcnow() -timedelta(minutes=1),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "yesterday", "calltypeid": results[0],"routeid": results[1]},"time": datetime.utcnow() -timedelta(minutes=1) + timedelta(days=1),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "1weeks", "calltypeid": results[0],"routeid": results[1]},"time": datetime.utcnow() -timedelta(minutes=1) + timedelta(weeks=1),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "2weeks", "calltypeid": results[0],"routeid": results[1]},"time": datetime.utcnow() -timedelta(minutes=1) + timedelta(weeks=2),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "3weeks", "calltypeid": results[0],"routeid": results[1]},"time": datetime.utcnow() -timedelta(minutes=1) + timedelta(weeks=3),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        results = cursor.fetchone()
    connection.close()
    client = InfluxDBClient('10.101.163.33', 8086, 'mmartinez2', 'Password123', 'sd')
    client.write_points(ls)
    print("completed")
scheduler = BlockingScheduler()
scheduler.add_job(pull_data, 'interval', minutes=1)
scheduler.start()

or
# !/usr/bin/python

from influxdb import InfluxDBClient
from apscheduler.schedulers.blocking import BlockingScheduler
import threading
import time
import datetime
import requests
import pypyodbc
from datetime import date
import logging
logging.basicConfig()

def pull_data():
    #threading.Timer(60.0, pull_data).start() # called every minute
    ls = []
    c = 0
    connection = pypyodbc.connect("DRIVER={SQL Server};SERVER=10.101.162.240;UID=user_test;PWD=Admin123;DATABASE=tcs_awdb")
    cursor = connection.cursor() 
    SQLCommand = ("SELECT Termination_Call_Detail.CallTypeID, Termination_Call_Detail.RouteID, Count = SUM(CASE WHEN Termination_Call_Detail.CallDispositionFlag = 1 THEN 1 ELSE 0 END), Duration = SUM(Duration), RingTime = SUM(RingTime), HoldTime = SUM(HoldTime), TalkTime = SUM(TalkTime), QueueTime = SUM(Duration - (RingTime + HoldTime + TalkTime)) FROM Termination_Call_Detail WHERE DateTime between DATEADD(minute,-6,GETDATE()) and DATEADD(minute,-1,GETDATE()) AND RouteID IS NOT NULL GROUP BY Termination_Call_Detail.CallTypeID, Termination_Call_Detail.RouteID")
    cursor.execute(SQLCommand)
    results = cursor.fetchone()
    while results:
        ls.append({"measurement": "handled","tags": {"type": "current", "calltypeid": results[0],"routeid": results[1]},"time": (datetime.datetime.now() - datetime.timedelta(minutes=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "yesterday", "calltypeid": results[0],"routeid": results[1]},"time": (datetime.datetime.now() - datetime.timedelta(minutes=1) + datetime.timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "1weeks", "calltypeid": results[0],"routeid": results[1]},"time": (datetime.datetime.now() - datetime.timedelta(minutes=1) + datetime.timedelta(weeks=1)).strftime("%Y-%m-%dT%H:%M:%SZ"),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "2weeks", "calltypeid": results[0],"routeid": results[1]},"time": (datetime.datetime.now() - datetime.timedelta(minutes=1) + datetime.timedelta(weeks=2)).strftime("%Y-%m-%dT%H:%M:%SZ"),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        ls.append({"measurement": "handled","tags": {"type": "3weeks", "calltypeid": results[0],"routeid": results[1]},"time": (datetime.datetime.now() - datetime.timedelta(minutes=1) + datetime.timedelta(weeks=3)).strftime("%Y-%m-%dT%H:%M:%SZ"),"fields": {"count": results[2], "duration": results[3], "ringtime": results[4], "holdtime": results[5], "talktime": results[6], "queuetime": results[7]}})
        results = cursor.fetchone()
    connection.close()
    client = InfluxDBClient('10.101.163.33', 8086, 'mmartinez', 'Password123', 'sd')
    client.write_points(ls)
    print("completed")
    print((datetime.datetime.now() - datetime.timedelta(minutes=1)).strftime("%Y-%m-%dT%H:%M:%SZ"))
scheduler = BlockingScheduler()
scheduler.add_job(pull_data, 'interval', minutes=5)
scheduler.start()

**Comment by aisbaa** [comment]
Hi, could you apply a little bit of formatting? It is a little bit hard to read it at the moment.

https://guides.github.com/features/mastering-markdown/
