### ISSUE TITLE
Tests are failing in master branch

### ISSUE THREAD

**Issue by aisbaa** [influxdata/influxdb-python#376]
Hello, tests are failing because of warning raised by pandas library. Are there plans to fixing it?

`FutureWarning: to_datetime is deprecated. Use self.to_timestamp(...)`

Have a [patch](https://gist.github.com/aisbaa/8e6c1b785eeef8d9923bb70b52e5ccac), but it's only as **workaround** not an actual solution.

**Comment by aviau** [comment]
I will as soon as I have time. But you are free to send a PR and I will merge it.

**Comment by aisbaa** [comment]
Don't have enough knowledge to create proper fix, if I got it right its by pure chance.

Here are change I've made https://gist.github.com/aisbaa/8e6c1b785eeef8d9923bb70b52e5ccac

Let me know if pull request would be more acceptable.

**Comment by aisbaa** [comment]
Any updates?

**Comment by aviau** [comment]
Please open a pull request.

**Comment by gansanay** [comment]
Addressed in #385
