### ISSUE TITLE
write() does not take protocol='line'

### ISSUE THREAD

**Issue by wtang6711** [influxdata/influxdb-python#377]
Trying to call:  
    dbHandle.write(data=lineData,protocol='line')

Exception: write() got an unexpected keyword argument 'protocol'

lineData is a list of string.
Why is that? Anything missing here?

**Comment by wtang6711** [comment]
pip install --upgrade  influxdb
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Requirement already up-to-date: influxdb in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: python-dateutil>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from influxdb)
Requirement already up-to-date: pytz in /usr/local/lib/python2.7/dist-packages (from influxdb)
Requirement already up-to-date: requests>=1.0.3 in /usr/local/lib/python2.7/dist-packages (from influxdb)
Requirement already up-to-date: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from influxdb)

**Comment by cadnce** [comment]
It seems your problem is the keyword `protocol` was introduced in a more recent version than has been released and published to pip.

However you can install the version you can see on master using the following command:
`pip install git+git://github.com/influxdata/influxdb-python.git`

HTH

**Comment by cadnce** [comment]
Version 4.0.0 has been released now so you can now use `protocol="line"` with the version on pip.

As such this issue can be closed
