### ISSUE TITLE
DataFrameClient retry on batches

### ISSUE THREAD

**Issue by dirkdevriendt** [influxdata/influxdb-python#378]
When writing medium to large dataframes (multiple 50K datapoints and up) we sometimes run into server errors (HTTP 500, timeout etc). I understand this could be considered outside of the scope for the client library, but if the error is caught outside of the batch loop we can't know what data was uploaded and have to restart the upload for the entire dataframe.

Ideally, when using the the batch_size option on the DataFrameClient.write_points function it would be aware of these errors and retry a batch if needed. There are a few retry decorators out there that could be of use (e.g. https://github.com/d0ugal/retrace).

Any thoughts? Would this be a valuable addition? Would you mind taking a dependency on a retry decorator?

**Comment by geethanjalieswaran** [comment]
+1

**Comment by rterbush** [comment]
+1, just running into this issue

500 error is leaving influxdb server spinning off and taking the server down with it as a result.

**Comment by rafaelcapucho** [comment]
+1

**Comment by xginn8** [comment]
I added retry logic on ConnectionError a few months back, I'll implement something similar for HTTPErrors with exponential backoff (see https://github.com/influxdata/influxdb-python/pull/435).
