### ISSUE TITLE
InfluxDBClient.create_database() Doesn't Support Names with Spaces

### ISSUE THREAD

**Issue by trent** [influxdata/influxdb-python#380]
InfluxDB allows for database names to have spaces, but the `InfluxDBClient.create_database()` method does not due to the query `self.query("CREATE DATABASE %s" % dbname)` not wrapping the dbname with double-quotes.  When you try to create a database with spaces using the method, a InfluxDBClientError is raised with a "error parsing query..." message.

**Comment by cadnce** [comment]
Looks like this has been already fixed on master, just needs to be released.
https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L488

I've updated it to use the `quote_ident` function used by all the other queries #395
