### ISSUE TITLE
DataFrameClient messes up DateTimeIndex in write_points()

### ISSUE THREAD

**Issue by gansanay** [influxdata/influxdb-python#390]
If you run the pandas tutorial example, the dataframe you query has the same values as the dataframe written but with the index messed up (values around 01-01-1970 00:00) because the timestamps are badly computed.

This doesn't affect the version of influxdb-python you get by pip install, but the GitHub master branch (and my main pull request #388 at this time) are affected: the line protocol is broken.

There is no test to assert that the queried dataframe is equal to the written one.

I will try to make a specific PR for this issue when possible.

**Comment by gansanay** [comment]
I fixed this issue in the master branch of my fork, and also created a branch for the PR. I need to add a test for this problem before creating the PR.

@aviau : Could you please take a look at the master branch of my fork and tell me which of my modifications you would like to keep in the original master?

**Comment by weiteli** [comment]
@gansanay: I am encountering the same problem, is the issue solved?

Thanks

**Comment by KoenR3** [comment]
At version 4.0.0 I also have this problem if I use the lines protocol.

**Comment by sebito91** [comment]
Should be resolved already, but if not please let me know and we can reopen.
