### ISSUE TITLE
query sometimes returns Nones in fields

### ISSUE THREAD

**Issue by zshimanchik** [influxdata/influxdb-python#397]
Using latest influxdb from docker: version 1.1.0. 
and latest influxdb-python: version 3.0.0.
I've got DB. twice a second several records are being wrote into it.
And once per second I want to fetch latest record:
```python
query = "select * from {measurement} where field1='{some_value}' order by time desc limit 1"
query.format(...)
result = self.influx_client.query(query)
```
and sometimes I've got result with Nones:
```python
{'lat': None, 'field4': 0, 'long': -74.01572744070317, 'time': '2016-12-12T08:50:46.839224064Z', 'field2': None, 'field1': 19.347733742922554, 'field3': None}
```
But if I take timestamp from response with None and retry request
```python
query = "select * from {measurement} where time='2016-12-12T08:50:46.839224064Z'"
query.format(...)
result = self.influx_client.query(query)
```
It returns without Nones
```python
{'lat': 40.84946721544548, 'field4': 0, 'long': -74.01572744070317, 'time': '2016-12-12T08:50:46.839224064Z', 'field2': -0.5012990435177983, 'field1': 19.347733742922554, 'field3': 3.1213}
```

**Comment by xginn8** [comment]
@zshimanchik can you reproduce this issue from the current release?

**Comment by xginn8** [comment]
Closing for now, please feel free to reopen if this problem is still occurring.
