### ISSUE TITLE
I found a bug in influxdb-python

### ISSUE THREAD

**Issue by JasonLZJ** [influxdata/influxdb-python#400]
I use python2.6 . When I use pip install influxdb , influxdb-python 4.0.0 will be setup.
But when I save data , It will touch off an error looks like : AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'
  I uninstall it and install influxdb-python 3.0.0 ,everyting is ok.
  I think the cause of the issue is "datetime.timedelta.total_seconds" was added in python2.7
  So I create this issue.

**Comment by aviau** [comment]
We won't fix it, because we deprecated python2.6 support. Sorry.

However, feel free to open a PR and we will merge it.
