### ISSUE TITLE
Client is unable to write data but returns true

### ISSUE THREAD

**Issue by jyotisaini19** [influxdata/influxdb-python#401]
Hi All

I am writing data to influx using influxdb-python client library.The client return true but doesn't write data points.It is able to creates database and measurement.
Influx db version : 1.10

code:

client=InfluxDBClient('IP', PORT, 'USERNAME', 'PASSWORD', 'cost_analysis')
logging.basicConfig(level=logging.ERROR, filename='/tmp/exception.log')
ts = time.time()
sttime = datetime.datetime.fromtimestamp(ts).strftime('%Y%m%d_%H:%M:%S - ')
i = datetime.datetime.utcnow().isoformat()
print i
date= i.split("T")
print date
filename="cost_via_comp.txt."+date[0];
print(filename);
try:
        f = open("/data/artifacts/"+filename,"r")
        for line in f:
                words = line.split("=")
                words[1] = words[1].strip('\n')
                json_body = [
                                    {
                                        "measurement": "cost",
                                        "tags": {
                                            "component": words[1],
                                        },
                                        "time": i,
                                        "fields": {
                                            "cost": float(words[0])
                                        }
                                    }
                                ]
                print json_body
                client.write_points(json_body)

except Exception, e:
        logging.exception("Exception : " +str(e)+ " time : "+ sttime)
        sys.exit()

**Comment by brabiega** [comment]
Hi, I had similar problem. I've updated influxdb to newest one from their repository (https://docs.influxdata.com/influxdb/v1.2/introduction/installation/) and suddenly it works like a charm.
