### ISSUE TITLE
create_database() got an unexpected keyword argument 'if_not_exists'

### ISSUE THREAD

**Issue by depohmel** [influxdata/influxdb-python#410]
Hello, i don't see if_not_exists argument anymore in source code, but docs (http://influxdb-python.readthedocs.io/en/latest/api-documentation.html) are still showing it. 
Woudl be nice to have deprecation warning instead of just deleting an argument.

**Comment by dankolbrs** [comment]
I noticed this too. The documentation build on readthedocs is a few releases behind.

This parameter was deleted in [commit 4e06277](https://github.com/influxdata/influxdb-python/commit/4e06277b203cd13433367b857e3f5f78d19d95b8). Latest build of the documentation on readthedocs is 

```
Release:	2.12.0
Date:	June 08, 2016
Keywords:	python, time series, database
```

**Comment by xginn8** [comment]
Can this issue now be closed? Docs are up to date with the latest build.
