### ISSUE TITLE
'list' object has no attribute 'get' in static_tags = data.get('tags', None)

### ISSUE THREAD

**Issue by tommytwoeyes** [influxdata/influxdb-python#413]
I've been trying to determine why my script (following this example: http://engineer.john-whittington.co.uk/2016/11/raspberry-pi-data-logger-influxdb-grafana/) would not insert my JSON data.

After I wrote a proper exception-handling clause, I got the following message. But I am not sure if it's caused by a problem with my data, or with something else:

`
  File "./logger.py", line 83, in <module>

    if not influx_client.write(json_body):

  File "/usr/local/lib/python2.7/dist-packages/influxdb/client.py", line 282, in write

    data = make_lines(data, precision).encode('utf-8')

  File "/usr/local/lib/python2.7/dist-packages/influxdb/line_protocol.py", line 111, in make_lines

    static_tags = data.get('tags', None)

AttributeError: 'list' object has no attribute 'get'
`

Here is a sample of my data object:
`
[{'fields': {'temperature': '71.6', 'humidity': '43.2'}, 'tags': {'run': '201702080522'}, 'time': 'Wed Feb  8 05:22:57 2017', 'measurement': 'dev'}]
`

**Comment by smolse** [comment]
Proper method for a list of data points is `write_points()`. Method `write()` accepts only a single data point and expects a dictionary.
