### ISSUE TITLE
pep257 compliance

### ISSUE THREAD

**Issue by pmenglund** [influxdata/influxdb-python#415]
Make the repo [pep257](https://www.python.org/dev/peps/pep-0257/) compliant.

There are currently 484 errors 😱

**Comment by sebito91** [comment]
That's fair, will work on this and let you know when it's ready. PEP is HARD! 👊

**Comment by aviau** [comment]
If we do this, it would be great to add a linter to travis.

**Comment by sebito91** [comment]
That's a really good call, will look into that as well.
