### ISSUE TITLE
Wrap exception in InfluxDBClientError

### ISSUE THREAD

**Issue by Don42** [influxdata/influxdb-python#416]
When trying to write  to influx and the database is not available a requests ConnectionError is raised.
This happens after three retries at this location [0]. This exception should be wrapped or replaced with an InfluxDBClientError to simplify error handling for the user of the library.

[0] https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L246

**Comment by PierreF** [comment]
I think InfluxDBServerError is more appropriate.

**Comment by Don42** [comment]
Well, it might be an error in the server (broken/down) or the client (configuration issue) or somewhere in between (network). Maybe add a superclass for all exceptions the module might raise and use that when you can't really define if it's a client or server issue.

**Comment by renderit** [comment]
+1

**Comment by Don42** [comment]
This isn't really fixed by #508. My issue is that a user of your library should not need to know what library you are using to write to the database to handle all errors. Currently I have to import requests myself to handle connection exceptions.

**Comment by sogrom** [comment]
> This isn't really fixed by #508. My issue is that a user of your library should not need to know what library you are using to write to the database to handle all errors. Currently I have to import requests myself to handle connection exceptions.

Totally agree, please wrap raise requests.exceptions.ConnectionError in InfluxDBServerError
User should not have to study your code to know that you are raisng some imported exceptions. 

In doc there are only two exceptions, that can be raised in your lib.
https://influxdb-python.readthedocs.io/en/latest/exceptions.html
