### ISSUE TITLE
SELECT query that starts with a blank line wont work using DataFrameClient

### ISSUE THREAD

**Issue by MicroJoe** [influxdata/influxdb-python#425]
When writing long queries I tend to put split them onto serveral lines. The parenthesis and backslash Python string merge methods will work, but not the multiline string if you dont start with the `SELECT` keyword on the first line.

Example that works:
```python
result = client.query("""select temperature from temperature 
where time > '2017-03-13 10:40:00.000' 
and time < '2017-03-13 12:30:00.000' 
order by time""")
```
Example that does not work but should IMO:
```python
result = client.query("""
select temperature from temperature 
where time > '2017-03-13 10:40:00.000' 
and time < '2017-03-13 12:30:00.000' 
order by time""")
```

Code location: https://github.com/influxdata/influxdb-python/blob/master/influxdb/_dataframe_client.py#L143

Proposed fix: Add a call to Python's str.strip() method on this line.

I can write a pull request if you are ok to merge it (should be one line of code + verifying tests results + maybe adding a new test for this scenario).

**Comment by ardave** [comment]
As a user, I might prefer the DataFrameClient to throw an exception if it is unable to return a DataFrame.

**Comment by AndreCAndersen** [comment]
This issue is addressed in pull [requests 404](https://github.com/influxdata/influxdb-python/pull/404).
