### ISSUE TITLE
Invalide time conversion in DataFrameClient.__convert_dataframe_to_lines

### ISSUE THREAD

**Issue by avk1956** [influxdata/influxdb-python#426]
Python 3.5.2
time = ((pd.to_datetime(dataframe.index).values.astype(int) /
precision_factor).astype(int).astype(str))

Test:
>>> dates = pd.date_range('1/1/2000', periods=8)
>>> df = pd.DataFrame(np.random.randn(8, 1), index=dates, columns=['A'])
>>> df.index
DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

>>> sec = pd.to_datetime(df.index).values.astype(int)
>>> print(sec)
[ 1380122624  -476971008  1960902656   103809024 -1753284608   684589056
 -1172504576  1265369088]
>>> print(pd.to_datetime(sec))
DatetimeIndex(['1970-01-01 00:00:01.380122624',
               '1969-12-31 23:59:59.523028992',
               '1970-01-01 00:00:01.960902656',
               '1970-01-01 00:00:00.103809024',
               '1969-12-31 23:59:58.246715392',
               '1970-01-01 00:00:00.684589056',
               '1969-12-31 23:59:58.827495424',
               '1970-01-01 00:00:01.265369088'],
              dtype='datetime64[ns]', freq=None)
>>> sec64 = pd.to_datetime(df.index).values.astype(np.int64)
>>> print(sec64)
[946684800000000000 946771200000000000 946857600000000000
 946944000000000000 947030400000000000 947116800000000000
 947203200000000000 947289600000000000]
>>> print(pd.to_datetime(sec64))
DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq=None)

**Comment by ccaapton** [comment]
I have the same problem.

**Comment by ccaapton** [comment]
Looks like this change f9bd6cc19728d4578717acf752268e9a884a602d breaks line protocol time conversion. If I use json protocol, the time is converted as expected.

**Comment by xginn8** [comment]
Is this issue still occurring? I cannot reproduce this locally against HEAD, all the times appear as expected.
