### ISSUE TITLE
Data queried not enough under InfluxDB 1.2.0

### ISSUE THREAD

**Issue by hongquan** [influxdata/influxdb-python#434]
In InfluxDB 1.2.0, the data returned [is chunked by 10,000](https://docs.influxdata.com/influxdb/v1.2/guides/querying_data/#maximum-row-limit) rows, including `"partial":true` to indicate this.
`influxdb-python` currently doesnot support this feature and hence, leaves missing data.

**Comment by hongquan** [comment]
To let you have idea where the `"partial":true` tag is, I include a screenshot here:
![selection_124](https://cloud.githubusercontent.com/assets/314607/24716623/d8925c04-1a59-11e7-816e-8f97071045c4.png)

**Comment by nicolajkirchhof** [comment]
This is related to https://github.com/influxdata/influxdb/issues/7879. 
If you seek for a quick fix, try setting 'max-row-limit = 0'  in your influxdb.conf to get the full data range.

**Comment by bradmcl** [comment]
So, https://github.com/influxdata/influxdb-python/pull/418 which was merged allows you to work around this issue.

Arguably, having both chunked and chunk_size parameters feels a bit redundant, as they appear to be interdependent.  Doesn't chunk_size != 0 imply chunked = True?

And there is still the issue that if you do not specify chunking and the server applies the max-row-limit, you will silently get fewer results than you expect.

Having defaults of chunked=True and chunk_size=10,000 would less surprising to the user, eliminate the issue of server overload, and have no impact on queries returning < 10,000 results.

**Comment by aviau** [comment]
> Doesn't chunk_size != 0 imply chunked = True?

I think chunk_size was introduced after.

but yes, a PR for this would be welcome. however we need to keep chunked for backwards compatibility
