### ISSUE TITLE
Exception is too broad.

### ISSUE THREAD

**Issue by Fatekiller23** [influxdata/influxdb-python#437]
hi, i get this Exception when i use a wrong port number.
`influxdb.exceptions.InfluxDBClientError: 400: Bad request syntax ('new_issueline msg="Right Vertical Drive Fault" 1492937769000000')
`
this make me confused,because my request syntax is not wrong.
So, how about narrow the exception?

**Comment by aviau** [comment]
The exception text comes from the server. I think it should be solved there instead.

**Comment by Fatekiller23** [comment]
okay, i just think it can save much time for newbie although that fix seems trivial 😃
