### ISSUE TITLE
Database can be created with non-existent credentials

### ISSUE THREAD

**Issue by nargiza-sarkulova** [influxdata/influxdb-python#438]
I'm using Ubuntu 16.10, InfluxDB v1.2.2, influxdb-python v4.1.0.
I noticed that I can pass non-existent user credentials to InfluxDB client, create a database and write data:

```
from influxdb import InfluxDBClient

influx_client = InfluxDBClient(host='localhost', port=8086, username='not_existing_user', password='whatever', database='test_db')
influx_client.create_database('test_db')

point = {
    'time': '2017-04-24 09:58:55',
    'measurement': 'test',
    'fields': {
        'field1': 'test1'
    }
}
influx_client.write_points([point])
```

I have a standard Influx setup, meaning that meta and data directories are default ones and their owner:group is `influxdb:influxdb`. I don't have any other DB users except for a defult `root` user. 

This is a very bizarre behaviour so maybe I'm missing something here.

**Comment by xginn8** [comment]
According to influxdb documentation, auth is disabled by default in the conf file. Enabling auth should fix this issue. (https://docs.influxdata.com/influxdb/v1.2/query_language/authentication_and_authorization/)

**Comment by nargiza-sarkulova** [comment]
Ah, should've looked in docs right away! Thanks, closing this.
