### ISSUE TITLE
improved documentation for timestamp in points

### ISSUE THREAD

**Issue by bsholdice** [influxdata/influxdb-python#444]
I can't determine what the format for my points should be. perhaps I've missed something in the docs. If not, could you please describe what time format write_points expects?

I try epoch nanoseconds but it is not parsed:

```python
  File "/usr/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
           │             │     │      └ 1
           │             │     └ 5
           │             └ 1493920000000000000
           └ <module 'datetime' (built-in)>
OverflowError: signed integer is greater than maximum
```

**Comment by xginn8** [comment]
In the examples from the tutorial, you can see the timestamps in python datetime format (https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial.py)
