### ISSUE TITLE
pd.tseries.period.PeriodIndex has moved with pandas version 20.1

### ISSUE THREAD

**Issue by patrickhoebeke** [influxdata/influxdb-python#446]
Hello,

I've just noticed that for some use cases, the library does not work anymore with the new version of pandas v20.1.
In pandas 20.1, stuff related to tseries has been moved/dropped.
So references to "pd.tseries.period.PeriodIndex" should be replaced by "pd.PeriodIndex"

Patrick

**Comment by sebito91** [comment]
Should be fixed on #454 and #457
