### ISSUE TITLE
chunked query

### ISSUE THREAD

**Issue by adisD** [influxdata/influxdb-python#450]
our database keeps more than 50000 records. The objective is to read all records in order to reason on each particular record but query returns 10000 records. What is best practice here and what are examples on python code that will work according to scenario above?

**Comment by adisD** [comment]
Anyone please: this cannot be that difficult question. 

I have tried both like below:

client.query(queryString, chunked=False, chunk_size=50000) returns 10000
and 
client.query(queryString, chunked=True, chunk_size=50000) does not return at all

**Comment by samhatchett** [comment]
by "records", do you mean series, or points? if you are talking about getting more than 10k points in a query response, then it could be a server-side issue - https://github.com/influxdata/influxdb/issues/8222

there's a [note in the documentation](https://docs.influxdata.com/influxdb/v1.2/administration/config#max-row-limit-0) for the relevant config option:

> In versions 1.2.0 and 1.2.1, the max-row-limit option is set to 10,000 by default.

**Comment by pkittenis** [comment]
Max chunk/result size is set by server. If the client request exceeds the server limit the result will be truncated _by server_.

`client.query(queryString, chunked=True)` should give you a chunked response which, when iterated on, will give all results. Chunk size is best left to server to assign (default when `chunk_size=0`).
