### ISSUE TITLE
With pandas 0.20.1, DataFrame / write_points call fails with module ‘pandas.tseries’ has no attribute ‘period’ 

### ISSUE THREAD

**Issue by lraynaud** [influxdata/influxdb-python#456]
Please, let me know if the below is a known issue. And yes, I use Python 3.6, not officially supported, nonetheless this bug sounds important enough to be reported:    

With pandas 0.19.2, the python-influxDB demo sample given with the Tutorials - pandas works as expected with Python 3.6 (see URL http://influxdb-python.readthedocs.io/en/latest/examples.html). 
I am using Python 3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00)

ipdb> client.write_points(df, 'demo')
True

With pandas 0.20.1, client.write_points fails and the stack trace shows:
ipdb> client.write_points(df, 'demo')
...
_ client.write_points(df, 'demo')_
_ File "/Users/_____/anaconda/lib/python3.6/site-packages/influxdb/dataframe_client.py", line 117, in write_points_
_ numeric_precision=numeric_precision)_
_ File "/Users/_____/anaconda/lib/python3.6/site-packages/influxdb/dataframe_client.py", line 237, in convertdataframe_to_lines_
_ if not (isinstance(dataframe.index, pd.tseries.period.PeriodIndex) or_
AttributeError: module 'pandas.tseries' has no attribute 'period'

Thanks,
Lionel

**Comment by sebito91** [comment]
There are two PR's in now for this! #454 and #457...will update shortly.
