### ISSUE TITLE
Bug after upgrading from pandas 0.18.1 to pandas 0.20.2 

### ISSUE THREAD

**Issue by t-pfaff** [influxdata/influxdb-python#462]
`write_points()` now throws an error for `if not (isinstance(dataframe.index, pd.tseries.period.PeriodIndex) or` (line 118 in `_dataframe_client.py`:

> AttributeError: module 'pandas.tseries' has no attribute 'period'

**Comment by sebito91** [comment]
@t-pfaff which version of the influxdb-python module are you using? We just patched the code (#457) to address this in the latest release. Can you please try the 4.1.1 release?

https://pypi.python.org/pypi/influxdb/4.1.1

**Comment by t-pfaff** [comment]
@sebito91 I used influxdb 3.0.0 Upgraded to 4.1.1 and it works. Thanks!
