### ISSUE TITLE
Add support for streamed chunks when making large queries

### ISSUE THREAD

**Issue by msohcw** [influxdata/influxdb-python#478]
Currently I've written a system that takes advantage to requests streaming capability to avoid loading all of the chunks into memory at once. Generally this seems faster and better than what is currently provided which loads all the chunks immediately. Could support be added for a generator that lazily loads chunks from buffer?

**Comment by mpas** [comment]
I have a need to export a large number of rows and seem to run in the same issue that you have solved. Could your solution be used to export these large numbers?

**Comment by msohcw** [comment]
Essentially, I wrote a wrapper around InfluxDB and extended it with a `lazy_query` method. I then used `requests` in-built streaming capability to stream HTTP requests to InfluxDB. I would then return the stream as a generator.

**Comment by sebito91** [comment]
Fixed in #753
