### ISSUE TITLE
DataFrameClient issue - seems does not process correctly DateTimeIndex dates

### ISSUE THREAD

**Issue by JohnSamler** [influxdata/influxdb-python#479]
I'm having problems uploading dataframes into InfluxDB, using write_points.

The problem is due to this part of the code:

File _dataframe_client.py

```
        # Make array of timestamp ints
        if isinstance(dataframe.index, pd.PeriodIndex):
            time = ((dataframe.index.to_timestamp().values.astype(int) /
                     precision_factor).astype(int).astype(str))
        else:
            time = ((pd.to_datetime(dataframe.index).values.astype(int) /
                     precision_factor).astype(int).astype(str))
```

That int cast doesn't work in my code. I tested just casting datetime's into ints and this is what i get:

```
    In [24]: numpy.datetime64('2016-01-05T00:00:00.000000000').astype(int)
    Out[24]: -1226113024
    In [25]: numpy.datetime64('2016-01-04T00:00:00.000000000').astype(int)
    Out[25]: 630980608
    In [26]: numpy.version.version
    Out[26]: '1.11.3'
```

I had to modify the code to cast to np.int64 for it to work (not using PeriodIndex):

```
        # Make array of timestamp ints
        if isinstance(dataframe.index, pd.PeriodIndex):
            time = ((dataframe.index.to_timestamp().values.astype(int) /
                     precision_factor).astype(int).astype(str))
        else:
            time = ((pd.to_datetime(dataframe.index).values.astype(np.int64) /
                     precision_factor).astype(np.int64).astype(str))
```

Don't think the cast as coded currently is correct, or a case is missing.

**Comment by patrickhoebeke** [comment]
I confirm the issue.
On my Ubuntu, I do not have the issue, the casting to int generates the correct Epoch required by Influx.
On Windows, the conversion ins rather chaotic if using 'int'.
Casting to np.int64 solves the issue on both OS.

So I propose the following modification:
```python
# Make array of timestamp ints
if isinstance(dataframe.index, pd.PeriodIndex):
    time = ((dataframe.index.to_timestamp().values.astype(int) /
        precision_factor).astype(int).astype(str))
else:
    time = ((pd.to_datetime(dataframe.index).values.astype(np.int64) /
        precision_factor).astype(np.int64).astype(str))
```

As a side note, from a performance point of view, direct casting seems to be more performant. For example with a DataFrame with 1 million rows:
```python
%timeit (pd.to_datetime(dataframe.index).values.astype(np.int64) /  1e9).astype(np.int64).astype(str)
```
> 10 loops, best of 3: 113 ms per loop
```python
%timeit str(np.int64(np.int64(pd.to_datetime(dataframe.index).values) /  1e9))
```
> 100 loops, best of 3: 5.65 ms per loop

**Comment by patrickhoebeke** [comment]
It seems that it is related to the number of bits used by the conversion to int (32 bits VS 64bits).
I did not have the issue on my machine (running 64bits Linux) but my colleague has  the issue on his machine (Windows 64bits). But it looks like the default int type on Windows is 32bits (even on 64bits machine) see [here](https://stackoverflow.com/questions/36278590/numpy-array-dtype-is-coming-as-int32-by-default-in-a-windows-10-64-bit-machine).
I could reproduce the bug on my Linux machine by simply using np.int32 in place of int.
So it looks like astype(int) converts to 32bits on some machines and to 64bits on others.
Using np.int64 solved the issue.
I've just  created a pull request that solves the issue. (sorry it is split in two commits as I was wrong with the first fix)

Two remaining questions:
1. Is this fix compliant with 32bits machine? If fear that if we want to provide nanoseconds timestamps inputs to Influx, np.int64 is a requirement. So should it be part of some check when running the code?
2. I am not sure whether a specific unittest is required

**Comment by patrickhoebeke** [comment]
I've just made a cleaner pull request here : https://github.com/influxdata/influxdb-python/pull/507

**Comment by mousumipaul** [comment]
I am also facing the same error. I tried the following code:
from datetime import datetime
from influxdb import DataFrameClient
import pandas as pd
a = datetime.now()
times = []
times.append(a)
df = pd.DataFrame({'A':[5]}, index=times )
client = DataFrameClient('XXX.XXX.XX.XXX', 8086, 'XXX', 'XXX', 'XXXX')
client.write_points(df, 'M1', protocol='json')

I got the following error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/influxdb/_dataframe_client.py", line 125, in write_points
    field_columns=field_columns)
  File "/usr/local/lib/python2.7/site-packages/influxdb/_dataframe_client.py", line 194, in _convert_dataframe_to_json
    dataframe.index = dataframe.index.to_datetime()
AttributeError: 'DatetimeIndex' object has no attribute 'to_datetime'

**Comment by patrickhoebeke** [comment]
@mousumipaul 
I think it is related to the version of pandas you are using.
It seems that pandas.DatetimeIndex.to_datetime exists in pandas 0.22 but disappeared in version 0.23
https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DatetimeIndex.html
https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DatetimeIndex.html
Much less methods in 0.23

**Comment by mousumipaul** [comment]
@patrickhoebeke 
Thanks Patrick for the answer. You are right. It is the problem with pandas. I have changed the pandas version from 0.23.0 to 0.22.0 and it worked perfectly.
