### ISSUE TITLE
Error inserting more than 900 entries at once

### ISSUE THREAD

**Issue by johncarmack1984** [influxdata/influxdb-python#480]
Running influxDB v1.3.1 on macOS Sierra

Attempting to insert stock market data in quantities larger than 1000 entries leads to this error in jupyter:

> InfluxDBServerError: b'{"error":"[shard 19277] open /usr/local/var/influxdb/data/quandlwiki/autogen/19277: too many open files"}\n'

and this error in the terminal window running influxd:

> Failed to open shard: 18931: [shard 18931] open /usr/local/var/influxdb/data/dbname/autogen/18931: too many open files service=store

**Comment by aviau** [comment]
This is a server error, please open an issue in the server repository https://github.com/influxdata/influxdb
