### ISSUE TITLE
Adding multiple points with a single call to write

### ISSUE THREAD

**Issue by tditrani** [influxdata/influxdb-python#481]
Is it posable? I've tried separating dicts with a comma like,
test_1 = [{"measurement" : measurment, "tags" : {'tag_1': 'tag_1', 'tag_2': 'tag_2'},
           "fields" : {'feild_1': 6, 'feild_2': 8}},
          { "measurement": measurment, "tags": {'tag_1': 'tag_1', 'tag_2': 'tag_2'},
           "fields": {'feild_1': 7, 'feild_2': 10}},
          {"measurement" : measurment, "tags" : {'tag_1': 'tag_1', 'tag_2': 'tag_2'},
           "fields" : {'feild_1': 10, 'feild_2': 11}},]
,but only the last one gets added.

**Comment by xginn8** [comment]
If you are writing points at the same time to the same measurement, only the last point will persist. Otherwise, you can pass a timestamp to differentiate.
