### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by mindlessbrain** [influxdata/influxdb-python#483]
Think it would be useful to add a method to backup all DBs. What do you guys think?

**Comment by ainguyen** [comment]
That would be a great idea

**Comment by zodiac403** [comment]
Is this issue still active?

A method to backup a single DB or all DBs would be quit handy. I'm thinking about something similar to `influxd backup`

**Comment by golanudelamare** [comment]
Is there any update regarding this matter?

**Comment by jiri-moc** [comment]
It would be really nice to have this feature

**Comment by Moradf90** [comment]
Is there any update?

**Comment by sebito91** [comment]
No updates here to adding this into the python client. I'm not sure this is actually a feature that we should address here, as the `influxd` binary gives you this now.
