### ISSUE TITLE
Regex or escaping problem

### ISSUE THREAD

**Issue by colundrum** [influxdata/influxdb-python#484]
Hi,

I try to do a simple query in my python script but I've a problem and I need your help.

In InfluxDB cli : No problem
`select Percent_Free_Space from win_disk where time > now() - 1m and "instance" =~ /D:\\MountPoints\\DB10_DATA/ and "host" =~ /DB01/`

In Python script : Problem
`for i in instances_list:
    query = 'select last(percent_free_space) from "win_disk" WHERE "instance" =~ /{}/ AND "host" =~ /{}/'.format(i, 'DB01')
    query_percent_free_disk_space_instance = client.query(query)
    response_percent_free_disk_space_instance = list(query_percent_free_disk_space_instance)
    print(response_percent_free_disk_space_instance)`

instances_list are built using :
`query_win_disk_instance = client.query('SHOW TAG VALUES FROM "win_disk" WITH KEY = "instance" WHERE host =~ /{0}/'.format('DB01'))
response_win_disk_instance = list(query_win_disk_instance.get_points())
instances_list = [e['value'] for e in response_win_disk_instance]`

Error :
`influxdb.exceptions.InfluxDBClientError: 400: {"error":"error parsing query: error parsing regexp: invalid escape sequence: `\\M` at line 1, char 68"}`

Have you a solution at this problem ?

Thanks

**Comment by xginn8** [comment]
Is this issue still occurring in the latest release?

**Comment by xginn8** [comment]
Closing due to lack of response -- we can reopen if needed.
