### ISSUE TITLE
DataFrameClient returns a list of DataFrames instead of a single dataset

### ISSUE THREAD

**Issue by jameslamb** [influxdata/influxdb-python#496]
I have really enjoyed working with the `DataFrameClient` in this module. It makes it easy to do data science on data in InfluxDB.

I've noticed that for the data model + query pattern I'm using, the client returns a list of DataFrames instead of one DataFrame. For example:

```
query_body = """
SELECT mean(value)
FROM measure_1, measure_2, measure_3
WHERE time > \'2017-08-01T10:00:00Z\' AND time < \'2017-08-10T10:00:00Z\'
GROUP BY time(1h)
"""
response = db_client.query(query_body)
```

returns a dictionary of DataFrames, one for each measure.  I found myself using something like the following to combine the resulting list of DFs back into a single DF, relying on the fact that they'll all have a similar DateTimeIndex:

```
# Parse dictionary into a list of DataFrames, change column names
df_list = []
for name in response.keys():
    thisDF = response[name]
    thisDF.columns = [name]
    df_list.append(thisDF)

# Join the results (each DF will have a dateTimeIndex already)
outDF = df_list[0]
if len(df_list) > 1:
    for nextDF in df_list[1:]:
        outDF = outDF.join(nextDF)
```

I'm wondering:

1) Does the client already have this functionality (returning a single DataFrame for a query pattern like mine)?
2) If not, would it be useful for me to create a PR adding this as optional functionality?

Thanks very much for considering these questions!

**Comment by chiamarc** [comment]
It seems to me that in most contexts you would want a separation of dataframes for each measurement, especially if those dataframes have multiple tags or fields beside value.  Alternatively, could you not use InfluxDBs native inner join?

**Comment by jameslamb** [comment]
@chiamarc that's fair, I wasn't thinking about the case where you're pulling more than just value. Please feel free to close this issue
