### ISSUE TITLE
Can not work, issue show KeyError: '[0] not in index', need your great help .thanks.

### ISSUE THREAD

**Issue by leonyan1314** [influxdata/influxdb-python#497]
Create pandas DataFrame
Create database: demo
Write DataFrame
Traceback (most recent call last):
  File "/Users/LeonYan/MyPython/QI/DF2influx.py", line 50, in <module>
    main(host=args.host, port=args.port)
  File "/Users/LeonYan/MyPython/QI/DF2influx.py", line 25, in main
    client.write_points(df, 'demo', protocol=protocol)
  File "/Users/LeonYan/Library/Python/2.7/lib/python/site-packages/influxdb/_dataframe_client.py", line 125, in write_points
    field_columns=field_columns)
  File "/Users/LeonYan/Library/Python/2.7/lib/python/site-packages/influxdb/_dataframe_client.py", line 220, in _convert_dataframe_to_json
    dataframe[field_columns].to_dict('record'))
  File "/Users/LeonYan/Library/Python/2.7/lib/python/site-packages/pandas/core/frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "/Users/LeonYan/Library/Python/2.7/lib/python/site-packages/pandas/core/frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "/Users/LeonYan/Library/Python/2.7/lib/python/site-packages/pandas/core/indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: '[0] not in index'

**Comment by leonyan1314** [comment]
MAC OS 10.12.1,python 2.7

**Comment by eric-guanwy** [comment]
I don't know whether you have got it resolved by now, and I just encountered the same keyerror issue today, for my situation it fixed by specifying the  attribute "columns" explicitly with a string type '0' when create a DataFrame.  As the code below:
  `  df = pd.DataFrame(data=list(range(30)),index=pd.date_range(start='2014-11-16',periods=30, freq='H'),columns=['0'])
`

**Comment by kiranmantri** [comment]
In fact, you can assign any string-based name to your columns.
If `columns=['something'] is suppressed, pandas assigns numerical id them.

*work: *
 `df = pd.DataFrame(data=list(range(30)),index=pd.date_range(start='2014-11-16',periods=30, freq='H'),columns=['0'])`

*doesn't work:*
`df = pd.DataFrame(data=list(range(30)),index=pd.date_range(start='2014-11-16',periods=30, freq='H'),columns=[0])`


*work:*
`df = pd.DataFrame(data=list(range(30)),index=pd.date_range(start='2014-11-16',periods=30, freq='H'),columns=['your_column'])`

**Comment by xginn8** [comment]
closing this since there's no issue

**Comment by techaddicted** [comment]
I know this issue is closed, but it looks like this is really an issue!
I also encountered this error, when trying out the example code for [influxdb-python with pandas](https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_pandas.py).

Can we get a fix for this?

**Comment by SatoshiNewton** [comment]
Actually, i fix it.
And i think it's still need to take, because the module need more compatibility to pandas DataFrame.
I would have pull request after i take more testing about pandas and Mac OS X.

**Comment by kiranmantri** [comment]
Hi @SatoshiNewton ,
Cool ! that's is the approach I applied on my end to solve the bug... and I believe that is right way to solved it (or at least to make influxdb-client more robust when dealing with Pandas dataframes).
