### ISSUE TITLE
ResultSet and values in different places in the output

### ISSUE THREAD

**Issue by n01knows** [influxdata/influxdb-python#498]
Hello

I'm getting different placement of mode and time:

ResultSet({'('ppm10', None)': [{'mean': 23.49, 'time': '2017-09-06T15:00:00Z'}]})
ResultSet({'('ppm10', None)': [{'time': '2017-09-06T15:00:00Z', 'mean': 20.39}]})

Queries were executed with one minute pause.

"SELECT mean(value) FROM ppm10 WHERE lat = '" + str(row[1]) + "'  AND long = '" + str(row[2]) + "' AND time > (now() - 1m) - 30m GROUP BY time(30m) ORDER BY time DESC limit 1"

Currently I'm using split to get only value from mean - 23,49 etc... But when mean placement is changing sometimes split does not work correctly.

Can you please advise how are you dealing with this?

Regards
Tom.

**Comment by vincent-legoll** [comment]
Could you please post your code, I think split() usage in this case looks suspect.

You shold access 'mean' like that

for p in rs.get_points():
  m = p['mean']
  print m

or something like that, use the python way, not the try-to-parse-a-string way...

**Comment by vincent-legoll** [comment]
@xginn8: would have been cool if you told us the closing reason.

**Comment by vincent-legoll** [comment]
What would be interesting to know is if you think something is wrong/missing from the documentation...

**Comment by n01knows** [comment]
Well it is hard to tell, for me python not so much experienced person it would be nice to know how to extract particular values from query output. But this can be so obvious from experienced python programmer than it would not be worthy to add to documentation :)

**Comment by xginn8** [comment]
Sorry about that! I closed the issue due to the lack of response from OP.
