### ISSUE TITLE
Implement CHANGELOG

### ISSUE THREAD

**Issue by sebito91** [influxdata/influxdb-python#499]
Would be nice to cut releases on a regular cadence, adding this to track progress on a release cycle + process.

**Comment by hvdklauw** [comment]
Yeah, not sure now if I can upgrade to version 5 because there is nothing to indicate backwards compatibility

**Comment by aviau** [comment]
See https://github.com/influxdata/influxdb-python/releases

**Comment by aviau** [comment]
![screenshot from 2018-01-15 15-15-53](https://user-images.githubusercontent.com/2706882/34960002-007b3fdc-fa07-11e7-8d30-759f1099a114.png)

**Comment by aviau** [comment]
@hvdklauw the breaking change is well explained.

**Comment by RossBarnie** [comment]
Yes, the release explains the low-level detail of the change, but as a user of InfluxDB, and not a developer on it, I have no idea which versions of InfluxDB would be incompatible without trawling through various versions of InfluxDB's source code.

While the release does provide a good explanation of the changes, a Changelog, along with a clear indication of InfluxDB versions affected by any breaking changes, would be more immediately accessible and readable.

**Comment by aviau** [comment]
influxdb-python is for programmers. If you use a program that uses influxbd-pyhton, this program should document what version of influxdb-python it supports.

**Comment by RossBarnie** [comment]
Ok, in that case let's look at it from a programmers' point of view. How do I know which versions of InfluxDB are no longer supported by the 5.0.0 version of influxdb-python? What versions of InfluxDB can I say I support to people who use my library which depends on influxdb-python? Of course I can go look for myself, the point is that if there's a single source of truth (ie in the Changelog), then you're saving X amount of time for every developer or sysadmin who just wants to know if it's safe to upgrade this library for a given version of InfluxDB. It provides value to the library and respects other developers' and sysadmins' time.

**Comment by aviau** [comment]
> How do I know which versions of InfluxDB are no longer supported by the 5.0.0 version of influxdb-python?

We don't even know ourselves.
