### ISSUE TITLE
Precision option in SeriesHelper options

### ISSUE THREAD

**Issue by appunni-dishq** [influxdata/influxdb-python#501]
Unable to set precision when using 

> SeriesHelper Class

Please help me here, also when I send timestamp in seconds it gets converted to nanoseconds since epoch and getting a date near epoch. If you can help on setting this in Influxdb as default as well it will be helpful 

https://stackoverflow.com/questions/46294051/influx-db-precision-setting-at-db-level

**Comment by appunni-dishq** [comment]
#502  I am doing a pull request to solve this issue

**Comment by appunni-dishq** [comment]
Referencing Stackoverflow question for future reference 

https://stackoverflow.com/questions/46294051/influx-db-precision-setting-at-db-level

**Comment by sebito91** [comment]
This is closed in #502 and #719
