### ISSUE TITLE
Missing get_list_measurements() function

### ISSUE THREAD

**Issue by brianbirir** [influxdata/influxdb-python#509]
From the [API documentation](http://influxdb-python.readthedocs.io/en/latest/api-documentation.html), `get_list_measurements()` has been listed as a method available for `InfluxDBClient` object.

However, after installing `v4.1.1` and trying to use the method, I get this error:

> Traceback (most recent call last):
>   File "influx.py", line 27, in <module>
>     pprint(get_measurements())
>   File "influx.py", line 25, in get_measurements
>     return client_db.get_list_measurements()
> AttributeError: 'InfluxDBClient' object has no attribute 'get_list_measurements'

I checked the `clients.py` file under `/usr/local/lib/python2.7/dist-packages/influxdb` and can confirm that the method is missing. This confirmation is the same after downloading the latest release ZIP file from the **Releases** page

**Comment by xginn8** [comment]
This function was added recently and is not available in the latest packaged release, only on the build from HEAD. See https://github.com/influxdata/influxdb-python/pull/402). The documentation you are looking at is from HEAD, not the latest stable release. Here are the API docs for the 4.1.1 release http://influxdb-python.readthedocs.io/en/stable/api-documentation.html. It will be available in the next versioned release.

**Comment by brianbirir** [comment]
Ok. Thank you @xginn8
