### ISSUE TITLE
Understanding how to write pandas DF with tags, to influxDB

### ISSUE THREAD

**Issue by laimaretto** [influxdata/influxdb-python#510]
Hi. I have a [3526 rows x 5 columns] DF. This is a snippet of it.

```
                        0             1                  2         3      4
0     2017-09-29 22:41:51     10.2.95.5   C1195_LF470_SARF   0.0.1.1  11993
1     2017-09-29 22:41:37     10.2.52.7   CF643_RCZ70_SARM  0.0.1.16  12102
2     2017-09-29 22:41:39    10.2.102.7   C1345_BQS70_SARF  0.0.1.17  18173
3     2017-09-29 22:41:41   10.2.23.212   CN165_FS470_SAR8   0.0.0.7  23525
4     2017-09-29 22:41:38     10.2.96.4   CF832_UY570_SARM   0.0.1.4   6162
```
So column 0 is the index(time), columns 1, 2 and 3 should be tags, and column 4 is my value.

I've inserted previously points into influxdb by using a dictionary, such as ...

```
bodyDB = [{
	"measurement": tbName,
	"tags":
	{
		"col1": col1,
		"col2": col2,
		"col3": col3
	},
	"time": col0,
	"fields":
	{
		"col4": col4
	}
}]
```

How can I accomplish the same but, instead of using the `write_points(bodyDB)`, issuing the same with the DF? I don't understand how to tell the `write_points()` which column is index, which are tags and which is value?
Thanks!

**Comment by xginn8** [comment]
You'll want to use the DataFrameClient for such a write. Parameters are listed here: https://github.com/influxdata/influxdb-python/blob/master/influxdb/_dataframe_client.py#L44, and an example can be found here: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_pandas.py. Let me know if that helps!

**Comment by laimaretto** [comment]
Hi! Thanks for the tips! So, I tried your suggestions (mainly following your example) and I got closer, though I could not yet accomplish my task ... This is what I did:

```
dictToList  = [this_is_a_list_with_data]
headers    = ['time', 'col1', 'col2', 'col3', 'col4']
df 	   = pd.DataFrame(dictToList, columns = headers)				
timeValues    = df[['time','col4']]
tags    = {'col1': df[['col1']], 'col2': df[['col2']], 'col3':df[['col3']]}
```

`timeValues` is `[3526 rows x 2 columns]` and `tags` has 3 columns each one of size `[3526 rows x 1 columns]`, which is equivalent to my original DF: `[3526 rows x 5 columns]`. So far, so good ...

In order to write the points to influx, I did the following:

```
dbConnDF = DataFrameClient(dbAddress, dbPort, dbUser, dbPassword, dbName)
dbConnDF.write_points(timeValues, tbName, tags)
```
After doing so, I get the following error ...
```
Must be DataFrame with DatetimeIndex or PeriodIndex.
```
It is weird because the first column of `timeValues` is a dateTime and is the same type that I used when using the `bodyDB` approach as shown before. Let me show you a snippet of `timeValues`:

```
                     time  col4
0     2017-09-30 13:57:37     11995
1     2017-09-30 13:56:39     12104
2     2017-09-30 13:56:49     18176
3     2017-09-30 13:56:57     23525
4     2017-09-30 13:56:39      6162
5     2017-09-30 13:56:57     17569
6     2017-09-30 13:57:29     11542
7     2017-09-30 13:57:46       983
```

Any hints? :-) ... thanks!

**Comment by xginn8** [comment]
Did https://github.com/influxdata/influxdb-python/issues/286#issuecomment-333391449 solve your problem? A missing index?

**Comment by laimaretto** [comment]
Hi @xginn8 ... yes, it did solve my problem!

I just had to upgrade the python-inxludb to the latest version with pip3 (sudo pip3 install influxdb) and it's now working like a charm:

```
Name: influxdb
Version: 4.1.1
Summary: InfluxDB client
Home-page: https://github.com/influxdb/influxdb-python
Author: UNKNOWN
Author-email: UNKNOWN
License: MIT License
Location: /usr/local/lib/python3.5/dist-packages
Requires: six, pytz, python-dateutil, requests
```

With this approach (inserting DF into influx), I am now able to insert a 100K rows-dataframe in 75seconds (before, looping over it and inserting row-by-row would take above 25min).

This great! Thanks!

Lucas

**Comment by xginn8** [comment]
awesome, glad it helped.
