### ISSUE TITLE
tag_columns and field_columns does not seem to work in DataFrameClient.write_points python API

### ISSUE THREAD

**Issue by chorus12** [influxdata/influxdb-python#512]
Good day to all, 
I'm using an infulxdb python api to write data from a Pandas to influx. 
Readthe docs does not say much on the parameters **tag_columns** and **field_columns** in  DataFrameClient.write_points and I suppose here you specify your TAGS and FIELD columns in a dataframe. 
I have a very straight forward dataframe:

the_timestamp(index) |   lot | tag | value | quality
2014-08-10 02:56:10 |14080612 | tag1 | 64.98 | Uncertain
2015-08-10 02:56:12 |15080612 | tag2 | 65.01 | Uncertain
2016-08-10 02:56:14 |16080612 | tag4 | 64.48 | Uncertain

with **the_timestamp** as index and **lot, tag, quality** as tags and **value** as a value

I use the following call `client.write_points(df, 'metrics', tag_columns=tags, protocol=protocol)`
and get the error message:

> KeyError: "['log' 'tag' 'quality'] not in index"

I'm not getting the point how to write the data. 
I've seen other posts and tried tags parameter in all possible ways but none seems to work. 
Appreciate any idea. 
Regards, 
Sergei.

**Comment by chorus12** [comment]
seems to work now.

**Comment by chintan-sheth** [comment]
I'm having the same issue. How did you fix it?

**Comment by chorus12** [comment]
Here is my code that worked. 
One IMPORTANT thing to remember - index in the dataframe must be datetime


from influxdb import DataFrameClient
host, port='192.168.0.222', 8086
user, password = 'root', 'root'
protocol = 'line'
dbname = 'your-db-name'
client = DataFrameClient(host=host, port=port, username=user, password=password, database=dbname)

# df_model_data - is the dataframe with actual data sent to influx
N = df_model_data.shape[0]
# this api does not work for datasets over 200,000 records - so I have to load data in batches
mln = 200000
n_iterations = N//mln
tags = ['attribute']
for k in range(0,n_iterations+1):
    try:
        client.write_points(df_model_data[k*mln : (k+1)*mln], 'my_tags', tag_columns=tags, protocol=protocol, batch_size=1000000)
    except Exception as ex:
        print(ex)
        notify('exception...')
    print(k*mln,(k+1)*mln)
