### ISSUE TITLE
Question - write_points() exception

### ISSUE THREAD

**Issue by roman1627** [influxdata/influxdb-python#515]
I am trying to write a json (seen below) into influxDB by using influxdb-python using the below code-

```
DBclient = client(host, port, user, password, dbname) 
influx_data = json.dumps(write_to_influx_json)
print influx_data
# Writing Data in Influx
DBclient.write_points(influx_data)
```

JSON -
 ```  
 [{
    "fields": [{
        "PATH": "/",
        "DISK_USED_PERCENT": "10"
    }, {
        "PATH": "/xxxxxxxxx",
        "DISK_USED_PERCENT": "0"
    }, {
        "PATH": "/dev/xxxxxxxxx",
        "DISK_USED_PERCENT": "0"
    }, {
        "PATH": "/xxxxxxxxx",
        "DISK_USED_PERCENT": "3"
    }, {
        "PATH": "/sys/xxxxxxxxx/xxxxxxxxx",
        "DISK_USED_PERCENT": "0"
    }, {
        "PATH": "/run/xxxxxxxxx",
        "DISK_USED_PERCENT": "0"
    }, {
        "PATH": "xxxxxxxxx",
        "DISK_USED_PERCENT": "0"
    }],
    "tags": {
        "host_identifier": "xxxxxx",
        "name": "mount_point_percentage"
    },
    "time": "xxxxx",
    "measurement": "xxxxxxx"
  }]
```

But i keep getting the below error -

`AttributeError: 'str' object has no attribute 'get'`

Can someone please point me in the right direction.

**Comment by xginn8** [comment]
You can write Python structures directly to influx -- no need to first serialize to json. Additionally, `fields` needs to be a dictionary, not a list. See the documentation for `write_points` for more information: https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdb.InfluxDBClient.write_points

Also the example might be helpful, see here: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial.py.
