### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by chiamarc** [influxdata/influxdb-python#519]
Hey folks,

Unless I'm doing something wrong, the 4.1.1 client does not have some of the methods documented on https://influxdb-python.readthedocs.io/en/latest/api-documentation.html.  For example, the InfluxDBClient object has no get_list_measurements() method.  I assume one now has to just do a query to get all/selected measurements but it would be nice if the docs were updated.

Thanks,
Marc

**Comment by xginn8** [comment]
Those docs are the `latest` version, i.e. the latest commit to HEAD. I
think you want to toggle to `stable` to get the documentation for the
latest released version (
http://influxdb-python.readthedocs.io/en/stable/api-documentation.html)
