### ISSUE TITLE
does the requests dependency really need to be >= 2.17.0

### ISSUE THREAD

**Issue by kentor** [influxdata/influxdb-python#522]
I am using the azure-sdk-for-python (< 2.0) and it seems to only work with requests < 2.11.0, so that conflicts with using this library which has a requirement for requests to be >= 2.17.0, see:

https://github.com/influxdata/influxdb-python/commit/a2ac2e8118c9220419eaf483685eeda491335612#diff-b4ef698db8ca845e5845c4618278f29a

Will this library still work with requests < 2.11.0?

**Comment by xginn8** [comment]
I ran a quick test with requests==2.10.0 and all the unit tests seemed to pass, so it might work, but ymmv. If you run into any trouble you might not get much support with such an old version of the library. Let us know the results!
