### ISSUE TITLE
Hosted documentation is out of date

### ISSUE THREAD

**Issue by boredstiff** [influxdata/influxdb-python#541]
The docs that are hosted as 'latest' are for 4.1.1 while the latest version is currently 5.0.0

https://influxdb-python.readthedocs.io/en/latest/

**Comment by xginn8** [comment]
@aviau can you force a rebuild of the docs? I can't access the readthedocs.io integrations to fix the webhook (looks like it may be disabled or otherwise non functional). 

@alexwidener I forked the docs here and forced a rebuild in the interim, see http://xginn8-influxdb-python.readthedocs.io/en/latest/

**Comment by aviau** [comment]
I'll take a look at this soon. Thanks for noticing!

**Comment by jflory7** [comment]
Curious if anyone had a chance to review this – I didn't realize I was looking at out-of-date docs until seeing this issue. I would guess I wasn't the only one. :slightly_smiling_face:

**Comment by xginn8** [comment]
@aviau if you add me as a maintainer on readthedocs.io, I can figure out why this is broken.

**Comment by aviau** [comment]
I can't. The maintainer would be @sebito91 .

Ping.

Can you add @xginn8 and me as maintainers please?

My username on readthedocs is

**Comment by aviau** [comment]
Ping @noahcrowley

**Comment by sebito91** [comment]
Was going to say, it wasn't me that's a maintainer on those docs...but I would update it if I could!

**Comment by aviau** [comment]
> Was going to say, it wasn't me that's a maintainer on those docs

Yeah sorry. I initially tagged you by mistake.

**Comment by noahcrowley** [comment]
I'll look into it.

**Comment by dajose** [comment]
hi @noahcrowley , have you had a chance on checking on this?

**Comment by xginn8** [comment]
@noahcrowley can you add myself and @aviau as maintainers in readthedocs, please?

**Comment by aviau** [comment]
We can probably just create a new readthedocs project.

**Comment by noahcrowley** [comment]
Hey, sorry for the delay, will try and get you added as maintainers ASAP @xginn8 and @aviau

**Comment by clslgrnc** [comment]
Any progress?

**Comment by noahcrowley** [comment]
Working on finding the owner of the readthedocs project. I've reached out to a few of the readthedocs support team to see if they could help.

**Comment by areski** [comment]
Sorry the late feedback, it seems that I was the original owner, it was a long time ago and completely forgot about that.

I have added @xginn8  as maintainer but @aviau doesn't seem to have an account on readthedocs.
Let me know if you need anyone else added.

**Comment by noahcrowley** [comment]
Can you add me as well, @areski?

**Comment by aviau** [comment]
My readthedocs username is ReAzem. Can you add me?

**Comment by areski** [comment]
@noahcrowley @aviau you are both added!

**Comment by xginn8** [comment]
Thanks for the help here @areski! I have rebuilt both stable and latest, so closing this issue.
