### ISSUE TITLE
1.3, 1.4

### ISSUE THREAD

**Issue by linearb** [influxdata/influxdb-python#543]
Curious how far away is this from supporting 1.3/1.4 with tsi?

**Comment by enavarro222** [comment]
Is it any news on it ?

**Comment by shakefu** [comment]
Is there any timeline for actually supporting the latest version of InfluxDB? 

/cc @aviau @xginn8 @sebito91

**Comment by jrajagopal** [comment]
+1

**Comment by sebito91** [comment]
Hi folks, sorry for the delay here but we’re looking to get this sorted in the next couple of weeks.

**Comment by shakefu** [comment]
FWIW we've published an open source bare bones Python client that works against InfluxDB 1.5 here: https://github.com/AxiomExergy/influx-client - doesn't implement the full API currently but it should work for basic write/read.

**Comment by luke-marshall** [comment]
Thanks @shakefu :)
Can anybody give any clarity around whether we've got 1.5 support in the official package yet?

**Comment by hyst329** [comment]
@luke-marshall I confirm that reading data from 1.5 works well (no code modification required).
