### ISSUE TITLE
inserting data to influxdb using pandas having redundant index, but gets saved as unique items

### ISSUE THREAD

**Issue by rounak9791** [influxdata/influxdb-python#548]
hi all
i am new to pandas and influx i have small snippet doing this

[dates = [datetime.datetime(2012, 5, 1), datetime.datetime(2012, 5, 2), datetime.datetime(2012, 5, 3)]
index = pd.DatetimeIndex(dates)
df = pd.DataFrame(data=list(range(3)),index=index)
client = DataFrameClient(host, port, user, password, dbname)
client.create_database(dbname)
client.write_points(df, 'test')

**i get output from db**
select * from test
name: test
time                0

1335830400000000000 0
1335916800000000000 1
1336003200000000000 2

**when i put similar dates**

[dates = [datetime.datetime(2012, 5, 1), datetime.datetime(2012, 5, 1), datetime.datetime(2012, 5, 3)]
index = pd.DatetimeIndex(dates)
df = pd.DataFrame(data=list(range(3)),index=index)
client = DataFrameClient(host, port, user, password, dbname)
client.create_database(dbname)
client.write_points(df, 'test')

**i get output from db**
select * from test
name: test
time                0

1335830400000000000 1
1336003200000000000 2

i need to insert all the 3  rows in the similar date case too.
could you please guide me to what i am missing here?

**Comment by arnauldvm** [comment]
Don't you need tags to distinguish your points?0
See also https://docs.influxdata.com/influxdb/v1.5/troubleshooting/frequently-asked-questions/#how-does-influxdb-handle-duplicate-points

**Comment by xginn8** [comment]
This behavior is expected based on how InfluxDB handles duplicate points.
