### ISSUE TITLE
How to export large number of rows to a csv file?

### ISSUE THREAD

**Issue by mpas** [influxdata/influxdb-python#550]
Hi there, i am trying to export a large number of rows to a csv file using the python client but i seem unable to do so. I am consistently blowing up the memory on the machine that runs the query. Any hints or pointers how this could be done would be appreciated.

**Comment by harshaddevale-tudip** [comment]
https://docs.djangoproject.com/en/1.11/howto/outputting-csv/#streaming-large-csv-files

**Comment by orchestor** [comment]
@mpas how do you  do it?

**Comment by mpas** [comment]
I created a sample script that takes 2 dates as an input from, until. Then the script generates a repeated export per day so i end with the data exported per day instead of the whole at once.
