### ISSUE TITLE
DataFrameClient.write_points() do not really write data into measurements.

### ISSUE THREAD

**Issue by SatoshiNewton** [influxdata/influxdb-python#553]
I found the example of DatAFrame write_points do not really write the points into database, when I check it with console.
The database and the measurements were created, but the points did not be written.
In the case of write_points without tag, the measurements was empty.
In the case of write_points with tag, the measurements contain the tag rather than the dataframe, point we want to write in.
I have been try to trace the source code, but I am not pretty sure the real reason now.
Because I am fresh in influxdb, i need to have more in-depth understand about tag, field, and value in influxdb.

Maybe I could help solve the issue #525 after I finish it.
If anyone knew more detail, could you help me?

**Comment by SatoshiNewton** [comment]
@xginn8 
Could you help me for this problem?

**Comment by xginn8** [comment]
If you are running the `tutorial_pandas.py` example, note that the final action is to drop the test database that the script wrote to: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_pandas.py#L38. If this is still an issue, we can reopen!
