### ISSUE TITLE
UDP Precision still locked at seconds

### ISSUE THREAD

**Issue by mdhausman** [influxdata/influxdb-python#554]
Debugging some issues getting InfluxDB metrics from our python services, I found that even [in the latest code](https://github.com/influxdata/influxdb-python/blob/master/influxdb/client.py#L500) UDP writes are locked into seconds precision when this hasn't been a necessity for influxdb since [early 2016](https://github.com/influxdata/influxdb/pull/5565).

Isn't it time for this to be updated? I'd be happy to jot up a quick pull request for it.

**Comment by aviau** [comment]
Feel free to open a PR

**Comment by xginn8** [comment]
Fixed by #557
