### ISSUE TITLE
SeriesHelper: Is it possible to set client in constructor?

### ISSUE THREAD

**Issue by mausquirk** [influxdata/influxdb-python#559]
I would like to set the client in the constructor of MySeriesHelper:

```
MySeriesHelper(client=self.db, time=timestamp.isoformat('T'), station=station, snow_depth=float(data[1]), fresh_snow=float(data[2]), air_temperature= float(data[3]))
```

What's the right way of doing this?

**Comment by xginn8** [comment]
See the `serieshelper.py` example here: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_serieshelper.py

I believe you'll want to extend the SeriesHelper class and pass in the client argument there.
