### ISSUE TITLE
client.py create and alter_retention_policy functions don't allow to change the shard group duration

### ISSUE THREAD

**Issue by szanics** [influxdata/influxdb-python#560]
The influxdb documentation recommends that you need to chose a specific shard group duration that matches your retention policy e.g. 1 day RP should have 1 hour shard group duration. Link to the docs:
https://docs.influxdata.com/influxdb/v1.4/concepts/schema_and_data_layout/#shard-group-duration-management

This parameter is missing from the client. I used the 4.1.1 version but this problem is still in 5.0.0

**Comment by xginn8** [comment]
We can add a `shard_duration` parameter -- but do note (from the link you pasted):
```
By default, the shard group duration is determined by the retention policy’s DURATION
```

So simply setting a retention policy will automatically set the proper shard group duration based on the table in the documentation.
