### ISSUE TITLE
Question/Help - Epoch Time with write_points

### ISSUE THREAD

**Issue by roman1627** [influxdata/influxdb-python#564]
I am currently trying to insert a JSON into InfluxDB using EPOCH as the timestamp, but i keep getting the below error, is it not possible to directly insert Data using Write Points to influx using EPOCH Time?
```python
write_data: signed integer is greater than maximum
```

```python
        # Writing Data in Influx
        try:
            DBclient.write_points(influxJson, time_precision='ms')
            return "true"
        except Exception as e:
            logging.info(e)
            return "false"
```

Where influxJson - 
```json
[{
	"fields": {
		"diskSpace": 44444444,
		"thing2": 444,
		"thing3": 444,
		"thing1": 444,
		"thing4": 444,
		"thing5": 444444,
		"cpuUtilization": 44444,
		"memoryUtilization": 4444
	},
	"tags": {
		"uniqueSystemId": "1234567890abcdefghijkl"
	},
	"time": "1518630588598",
	"measurement": "testingdev"
}]
```

**Comment by dbilli** [comment]
Are you sure your timestamp is correct?

$ date -d@1518630588598
Sat Jun 27 00:09:58 CEST 50093

Maybe it should be 1518630588:

$ date -d@1518630588
Wed Feb 14 18:49:48 CET 2018

**Comment by xginn8** [comment]
If you pass the `time` value as an `int` rather than `str` type, you will be able to write properly. The `time_precision` parameter doesn't work with `str`-type timestamps.
