### ISSUE TITLE
InfluxDBClient has no close() function as the documentation suggests.

### ISSUE THREAD

**Issue by Donovant** [influxdata/influxdb-python#566]
Trying to use the InfluxDBClient.close() function as referenced [http://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdb.InfluxDBClient.close](here).

I have printed the directory of InfluxDBClient which doesn't list close and you can see the error when trying to use this function. 

![screen shot 2018-03-05 at 11 29 24 am](https://user-images.githubusercontent.com/2975437/36992558-8a7a1870-2068-11e8-9443-408c51728af0.png)

**Comment by xginn8** [comment]
The `close` class method was added in 5.0.0, see commit 87683f41.
