### ISSUE TITLE
write multiple data points failed in influxdb1.5

### ISSUE THREAD

**Issue by aiworld8** [influxdata/influxdb-python#575]
Hi, I was trying to write multiple data points to a influxdb by running the sample python code ttps://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_sine_wave.py but not seeing the data in the database.

I tried to run the Insert command in influxdb CLI to add the data one by one, it works okay.

I did not find useful help yet though some people had encountered the same issue before. 

Any suggestions for me?

Thanks.

**Comment by jadhavmanoj** [comment]
@aiworld8 did you get any error?

**Comment by aiworld8** [comment]
No, I did not get any error, but just cannot see all the data appearing in the database after running the python code. I am running the code in Fedora Linux PC, Python version 2.7.

**Comment by xginn8** [comment]
Unfortunately InfluxDB 1.5 isn't supported yet -- closing in favor of #543.

**Comment by xginn8** [comment]
Reopening since this issue didn't show up in any of our tests

**Comment by xginn8** [comment]
Note that the final action in the script is to drop the `tutorial` database: https://github.com/influxdata/influxdb-python/blob/master/examples/tutorial_sine_wave.py#L61

I tested that tutorial script using Python3.6 and InfluxDB v1.5.4 and found no issue. Closing.
