### ISSUE TITLE
duplicated data when using dynamic measurement name

### ISSUE THREAD

**Issue by mehdipourfar** [influxdata/influxdb-python#577]
I have inherited a class from SeriesHelper. I want to have a dynamic serie name (e.x. 'events.stats.{server_name}'). ‌But I don't want to have server_name field for points because all points in each series have a same server_name. What should I do?

**Comment by xginn8** [comment]
I'm not sure I follow 100% what you're trying to do, but this issue sounds like something you'd want to use tags for (see https://docs.influxdata.com/influxdb/v1.5/concepts/glossary#tag). If you can give an example, I'm happy to reopen.
