### ISSUE TITLE
[Question] Include tags in get_points

### ISSUE THREAD

**Issue by Sykomaniac** [influxdata/influxdb-python#578]
Hi,

First of all apologies if this is the wrong place to raise this question! I execute the following query against an InfluxDB instance:

`SELECT MOVING_AVERAGE(active_percentage, 2) FROM "intel/procfs/cpu" WHERE "source" = 'testmachine' GROUP BY cpuID`

Which produces the following results (short-end for brevity):

```
name: intel/procfs/cpu
tags: cpuID=9
time                moving_average
----                --------------
1523620788607716143 0.4766438955258584

name: intel/procfs/cpu
tags: cpuID=10
time                moving_average
----                --------------
1523620788607716143 1.0825515341026533
```

Which is exactly what I want. However, when I execute this query in Python and attempt to convert the result into a dataframe (using get_points) the generated data frame omits any information about the associated tags.

As groupings contain averages with the same timestamp I need to include the cpuID as a column in the dataframe - otherwise I can't distinguish which average belongs to which CPU core.

Does anyone know if this is possible? Thanks and appreciate the help!

**Comment by Sykomaniac** [comment]
I solved this by making use of the dataframe client and then doing some post processing of the result:

```
      for key in datasets:
          df = datasets[key]
          # key[1][0][0] is the group by tag name
          # key[1][0][1] is the group by tag value
          df = df.add_prefix('{0}_{1}_'.format(key[1][0][0], key[1][0][1]))
```

This works for my use case and will hopefully help/inspire others!

**Comment by adityacj** [comment]
Can you show us a snippet of the query you used? And a bit more explanation of what the dataset contains?
