### ISSUE TITLE
Spaces in a dataframe column names breaks the line protocol

### ISSUE THREAD

**Issue by dmuiruri** [influxdata/influxdb-python#583]
An issue has been observed where a received dataframe contains un-escaped spaces in the column names (fields or tag keys), this results in a broken line protocol.

To reproduce:

`data = pd.DataFrame(np.random.random((10, 4)), columns=['a', 'b', 'First Entry', 'Second Entry'], index=pd.date_range(start='01/01/2000', periods=10))`
`client = DataFrameClient(database_name)`
`client.write_points(data, 'sample', protocol=line)`

Other solved issues related to this one: #520 #542

**Comment by xginn8** [comment]
Fixed by #584
