### ISSUE TITLE
ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by stef30360** [influxdata/influxdb-python#600]
Hello,
I have a problem, I can connect my database influxdb with jupyter notebook.
any ideas ?
regards
SR

ConnectionError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: //xxx.xxx.xxx.xxx:8086/query?q=SELECT++%2A++FROM++%22p1%22+++++&db=myhome (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10b6094a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

**Comment by xginn8** [comment]
Can you paste the client code that set up the connection? From that output it looks as though you're not connecting to the right hostname.

**Comment by stef30360** [comment]
`import argparse
import pandas as pd
%matplotlib inline

from influxdb import DataFrameClient
#host='localhost'
host='my_url_VM'
port=8086   # port of InfluxDB http API

"""Instantiate the connection to the InfluxDB client."""
user = 'root'
password = 'root'
dbname = 'home_assistant'

client = DataFrameClient(host, port, user, password, dbname)
fields = """ * """
measurement = """ "°C" """
filters = """WHERE "value" < 18.5 """
# query = """SELECT * FROM "°C" WHERE "value" < 18.5"""
query = """SELECT {} FROM {} {} """.format(fields, measurement, filters)
response = client.query(query)`

**Comment by Hassan-404** [comment]
I got the same issue but not solved yet
