### ISSUE TITLE
Import csv with multiple tables 

### ISSUE THREAD

**Issue by linguyen** [influxdata/influxdb-python#613]
Hi, I want to write to DataframeClient
I have a .csv file with many tables which have the same structure for example: 

market, branch a
day1, day2, value
1/1/2018,1/2/2018,1
1/3/2018,1/4/2018,5
[...] #more rows with the same structure as above.
market, branch b
day1, day2, value
1/1/2018,1/2/2018,2
1/3/2018,1/4/2018,5
[...] #more rows with the same structure as above.

I have used `pd.read_csv()` to read the file then also have separated those tables into subtables in pandas for parsing to influxdb. Here is one table in the csv file that I've got so far:
market: branch a 
        `0                        1                       2`
`1     day1                  day2                value`
`2     1/1/2018           1/2/2018          1 `
`3     1/3/2018           1/4/2018          5 `

My question is : do we have a way to read such .csv with multiple tables by DataframeClient? Since I read those subtables like the one I have above, I got error:

> TypeError: Must be DataFrame with DatetimeIndex or PeriodIndex.

**Comment by xginn8** [comment]
Once you read a csv into a dataframe, you can simply write that dataframe via DataFrameClient. I don't believe we want to support reading from csv natively from within the client.
