### ISSUE TITLE
Adding a new pypi maintainer

### ISSUE THREAD

**Issue by aviau** [influxdata/influxdb-python#614]
@xginn8, would you like to become a maintainer on pypi too?

This would allow you to tag and upload new releases.

The process is:

 1. Bump the version in ``influxdb/__init__.py`` (ex: 1c96ce244869b8d4fdee3b70bd441d707f42cd2c), following semver as well as possible.
 2. Tag, with the same format as the other tags

For example:
```
v5.2.0
* Finally add a CHANGELOG.md to communicate breaking changes (#598)
* Test multiple versions of InfluxDB in travis
* Add SHARD DURATION parameter to retention policy create/alter
* Update POST/GET requests to follow verb guidelines from InfluxDB
  documentation
* Update test suite to support InfluxDB v1.3.9, v1.4.2, and v1.5.4
* Fix performance degradation when removing NaN values via line
  protocol (#592)
* Dropped support for Python3.4
```

 3. ``./release.sh``

**Comment by xginn8** [comment]
yep, that sounds good to me! my username on pypi is the same as github, [xginn8](https://pypi.org/user/xginn8/)

**Comment by aviau** [comment]
I have added you as a maintainer!

**Comment by xginn8** [comment]
@aviau can you grant me push access to `master`? I can't cut a release it appears without approval for the change.

**Comment by aviau** [comment]
Sorry for not noticing this, I am on it!

**Comment by aviau** [comment]
I would have to disable most checks:
 - no longer require reviews
 - no longer require status checks

Or, you would have to open a PR that bumps the version.

For now, I have disabled the checks.

Do you prefer that we re-enable them and require pull requests?
