### ISSUE TITLE
MEASUREMENT in query not quoted

### ISSUE THREAD

**Issue by zxyz** [influxdata/influxdb-python#615]
Hello
Disclaimer: I just started python.

I'm using Python 3.6 on RHEL 7.4 with influxdb-python 5.2.0.

I've got to make queries on measurements which are named after the fqdn of the host, but unfortunately the MEASUREMENT does not get quoted in the query and therefore fails.

```
File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/influxdb/client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 403: {"error":"error authorizing query: grafana not authorized to execute statement 'SELECT interface, value FROM name.example.net WHERE metric =~ /.*prct/ AND time \u003e now() - 2m', requires READ on name"}
```

so the request goes to the MEASUREMENT "name" and not to "name.example.net"

my query line looks as follows:

`results = myclient.query('SELECT "interface","value" FROM {0} WHERE "metric" =~ /.*{1}/ AND time > now() - 2m'.format(args.hostname, xmode))`

querying on a measurement without the "." in its name works, as well as running the query on the influx cli with the fqdn quoted:

`SELECT interface, value FROM "name.example.net" WHERE metric =~ /.*prct/ AND time > now() - 2m`

So probably something like "quote_ident(measurement)" in the "delete_series" function is needed in the "query" function...which doesn't seem to be that simple, due to the queries beeing parsed as a complete string? 
Or is there a way around for me to parse the MEASUREMENT name with persisting quotes?

Thanks a lot!

**Comment by zxyz** [comment]
@xginn8 thats what I thought at first too. But:
- the `grafana` user has read access on all databases
- I authenticated as user `grafana` for the query via the influxdb cli which works
- I used exactly the same code to query a measurement which name doesn't  include and _special characters_ but just plain letters (no dots et al.).

The Problem is that the the name of the MEASUREMENT is cut after the first dot and InfluxDBClient tries to query the MEASUREMENT `name` instead of `name.examle.net` which doesn't exist and leads InfluxDBClient to the assumption that it doesn't have the propper access rights to the MEASUREMENT.  The error message is a bit misleading.

**Comment by xginn8** [comment]
To be clear that response comes from the database and is not generated by the client. From my testing if you encapsulate the `{0}` field with double quotes you should get back the values:

`results = myclient.query('SELECT "interface","value" FROM "{0}" WHERE "metric" =~ /.*{1}/ AND time > now() - 2m'.format(args.hostname, xmode))`

**Comment by zxyz** [comment]
@xginn8 thanks for the clarification.
quoting did the trick, could have thoght of that myself :man_facepalming: 
sorry for the noise and thanks a lot for the help!
