### ISSUE TITLE
#608 Breaks DataFrameClient

### ISSUE THREAD

**Issue by jlynn** [influxdata/influxdb-python#616]
`DataFrameClient.query` overrides `InfluxDBClient.query`, however it does not define the `method` keyword argument. This causes calls like `create_database` on `DataFrameClient` instances to fail.

**Comment by xezpeleta** [comment]
This bug has been driving me crazy! I've just started playing with InfluxDB python client and I thought I was doing something wrong.

Thanks! I hope the maintainers will merge the PR soon...
