### ISSUE TITLE
influxdb-python 5.2.0 doens't handle correctly unicode characters

### ISSUE THREAD

**Issue by guilhermesteinmuller** [influxdata/influxdb-python#620]
Hello. 

We have noticed that after the upgrade of the pip package from **5.1.0** to **5.2.0**, one of our tests that deals with unicode characters was failing [1][2]. 

We were forced to block version 5.2.0 of our global-constrains [3] in order to keep tests passing

[1] http://logs.openstack.org/09/583209/1/check/monasca-tempest-python-influxdb/a166cac/logs/testr_results.html.gz
[2] http://paste.openstack.org/show/726037/
[3] https://review.openstack.org/#/c/583274/

Is there any significant change between these two versions that could be the cause of this issue?

Thanks

**Comment by mattibf** [comment]
I investigated further, and reported another issue #633 , which describes more in detail, what happens.
@guilhermesteinmuller: Can you pls. check, if the issue reported by you can be closed?
