### ISSUE TITLE
How to install influxdb-python on windows 

### ISSUE THREAD

**Issue by Gudipatiambaprasas** [influxdata/influxdb-python#637]
Can you please explain how to install influxdb-python on windows I already installed influxdb and python separately

**Comment by shantanoo-desai** [comment]
Try using __Windows Subsystem for Linux__ and there you will obtain a bash shell which will provide you all facilities for installing the repo via `pip`

**Comment by ajeebkp23** [comment]
Try installing with `pip install influxdb`. It's working on my system.

**Comment by ajeebkp23** [comment]
> 
> 
> Can you please explain how to install influxdb-python on windows I already installed influxdb and python separately

Try installing with pip install influxdb. It's working on my system.
