### ISSUE TITLE
Doc seems outdated about supported InfluxDB versions

### ISSUE THREAD

**Issue by lafrech** [influxdata/influxdb-python#642]
https://influxdb-python.readthedocs.io/en/latest/include-readme.html

> This module is tested with InfluxDB v1.2.4, our recommended version. Though there have been v1.3 (initial TSI branch) and v1.4 releases these are not yet supported.

.travis.yml

```
env:
  - INFLUXDB_VER=1.2.4
  - INFLUXDB_VER=1.3.9
  - INFLUXDB_VER=1.4.2
  - INFLUXDB_VER=1.5.4
```

Or am I just confused?

**Comment by lafrech** [comment]
Actually, the whole documentation at https://influxdb-python.readthedocs.io/en/latest/ is outdated. I have no idea why.

Release: 4.1.1
Sep 13, 2017

**Comment by toabctl** [comment]
Still true. Doc is from 2017...

**Comment by xginn8** [comment]
duplicates https://github.com/influxdata/influxdb-python/issues/541, closing
