### ISSUE TITLE
windows utf8 prefix causes problems

### ISSUE THREAD

**Issue by jfcg** [influxdata/influxdb-python#659]
I exported some small table from MS SQL server to my windows 7 desktop as a csv file. This text file has 0xEF 0xBB 0xBF bytes as a prefix (some stupid windows/unicode convention to signify utf8 coding I guess) and some data after the prefix like:
A;B;1.0
A;B;1.5
A;E;1.1
C;D;2.0
I wrote a python 2.7 script on Linux to use the 1st field as measurement name, 2nd field as some tag name etc.
After importing this csv data to my InfluxDB 1.6.4 server, I see this output:
show measurements
A
A
C
"A" appears to repeat itself but one of them is actually "0xEF0xBB0xBFA" with a single record !
I was able to write that as a measurement name (with the latest python-influxdb).
However I could not delete that measurement with drop_measurement() method.

Also, in the influx (@influxdata) client shell, I could not type that measurement name to drop it either. I tried many byte escape styles but it did not work. It is not documented how to escape weird byte values like these on InfluxQL docs.
Thanks..

**Comment by aviau** [comment]
If it didn't work in the shell then you should open the issue on InfluxDB.

Feel free to open an issue here again if the problem really is in the python client.

**Comment by jfcg** [comment]
It also is a bug for the python library. You cant drop_measurement() you just created with it.

**Comment by aviau** [comment]
Sure, but if the bug is in InfluxDB then it isn't worth investigating here until it is fixed there.

**Comment by jfcg** [comment]
drop_measurement("\xEF\xBB\xBFA") fails with an InfluxDBClientError exception on python 2.7. I think the attempt does not even reach the server.

**Comment by aviau** [comment]
It does, this is raised when the server does not return expected return codes.

**Comment by aviau** [comment]
I'll reopen just in case.

**Comment by witekest** [comment]
@jfcg  Could you test with *influxdb-python==5.1.0*, please?
@aviau Is it possibly related with #633?
