### ISSUE TITLE
README.md and key=value parameters

### ISSUE THREAD

**Issue by rdxmb** [influxdata/influxdb-python#660]
README.md
-------------------

The README has as an example:
`client = InfluxDBClient('localhost', 8086, 'root', 'root', 'example')`

However, [this blog](https://www.influxdata.com/blog/getting-started-python-influxdb/) uses a key=value syntax:
`client = InfluxDBClient(host='localhost', port=8086)` , which would be more explicit (if the blog is correct)

Also, the connection via SSL is missing in the `README.md` . The blog uses
`client = InfluxDBClient(host='mydomain.com', port=8086, username='myuser', password='mypass' ssl=True, verify_ssl=True)` as an example, which should be
`client = InfluxDBClient(host='mydomain.com', port=8086, username='myuser', password='mypass', ssl=True, verify_ssl=True)`
I guess ?

If this is correct, this could be added to the README

**Comment by aviau** [comment]
Python allows you to call non-kwargs functions as if they were kwargs if you want.

The SSL connection isn't "missing". It just isn't presented.

Feel free to open a PR if you want.
