### ISSUE TITLE
Release 5.2.1

### ISSUE THREAD

**Issue by epa095** [influxdata/influxdb-python#661]
Commit caa9e7d044f0ac344200d45c385799207c311701 contains a useful bugfix. Since it does not change the API in any way it should be safe to release a bug-release 5.2.1, and release a corresponding wheel in pypi.

**Comment by flikka** [comment]
I would indeed also really appreciate that! We really need this, and currently have to implement a nasty workaround to get those last commits into the influxdb python library we use.

**Comment by aviau** [comment]
done
