### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by mufflon** [influxdata/influxdb-python#663]
Has development halted? There seems to be very little activity on this project while pull requests and issues seem to be mounting. What gives?

**Comment by aviau** [comment]
We do review pull requests but some of us don't put as much time into development anymore.

Feel free to open pull requests and we'll review them.

Most PRs that are stalling are lacking tests or response from the original author.

**Comment by lovasoa** [comment]
Is this project really still alive ? 
I made a pull request (#734) over four months ago and it still hasn't been reviewed.

**Comment by shantanoo-desai** [comment]
@lovasoa I just asked the Slack Channel and would they are internally discussing it whether to have the open-source community maintain it.

**Comment by lovasoa** [comment]
@shantanoo-desai : I'm not sure I understand you comment... You asked on influxdata's slack whether they want to drop maintenance of this project to make it exclusively community-maintained ? Isn't it the case already ?

**Comment by shantanoo-desai** [comment]
Well most of the maintainers are InfluxDB Employees, they tend to be jammed with work and if are discussing whether issue management and PR merges can be maintained by non-employees aka. open-source community that uses the library

**Comment by lovasoa** [comment]
`influxdb-python` is already maintained entirely by the community, and influxdata makes zero investment in it. See https://github.com/influxdata/influxdb-python/issues/735
