### ISSUE TITLE
DataframeClient returns int64 data for a float field

### ISSUE THREAD

**Issue by lovasoa** [influxdata/influxdb-python#665]
When a measurement in influxdb happens to have only round values in a float field, it is returned by the DataframeClient with an int64 dtype (instead of float64).

I would expect float fields to be returned as float64 columns in the returned dataframe, independently of their value.

Here is a notebook session that illustrates the bug:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/552629/50004262-f1bab800-ffa6-11e8-968c-3f059cc626c7.png">

[influx_client_bug.ipynb.zip](https://github.com/influxdata/influxdb-python/files/2680103/influx_client_bug.ipynb.zip)

**Comment by clslgrnc** [comment]
It would also be nice if sum, mean, ... of float fields where returned as float even if the result can be represented as an integer.
