### ISSUE TITLE
InfluxDBClientError: 400 when calling delete_series with no filter parameter

### ISSUE THREAD

**Issue by lafrech** [influxdata/influxdb-python#666]
Using Influxdb 1.7.4, this

```py
client = InfluxDBClient(HOST, database='test')
client.delete_series()
```

yields

    influxdb.exceptions.InfluxDBClientError: 400: {"error":"error parsing query: found EOF, expected FROM, WHERE at line 1, char 13"}

Looks like either `measurements` or `tags` should be provided.

This is not explicit in the method documentation. Perhaps a note should be added in the docs, and an exception raised if no filter is passed.

Or if it is actually possible to delete all measurements at once in Influxdb, then I guess `delete_series` ought to be fixed.

Or am I missing something?

**Comment by fl4p** [comment]
This is expected. You have to specify the measurement. If your intention is to drop the database don't use `delete_series`.
