### ISSUE TITLE
How to install influxdb-python on windows with no Internet

### ISSUE THREAD

**Issue by smbunn** [influxdata/influxdb-python#675]
I have a computer that must remain off the internet.  I need to run python to put data into an InfluxDB database on that computer.  I was going to get someone to write an interface to CSV files, but with 200,000 plus data points to load into Influx over 1 minute samples for the last 2 months this is getting unwieldy. Much better to just do it directly from Python.  However all the installs just say run pip from PowerShell and all assume you can get onto the internet.  Previously I have used 'wheels' to download the module I want to install and then used pip locally. 
Is there a InfluxDB wheel?  How else can I do this?

**Comment by aviau** [comment]
This isn't a support forum, so I will close this issue.

You can download the package from pypi and install it locally.
