### ISSUE TITLE
DataFrameClient not Working on Raspberry Pi (general Examples)

### ISSUE THREAD

**Issue by pickmylight** [influxdata/influxdb-python#685]
Your examples are not working on Influx 1.7.4 on Raspberry Pi 

I tried severeal ways to get Dataframes working, but each time I push something in, I get a True response from my Influx, but there is absolutely no data stored in my database.

Even with your example from DataFrame, I got the same results

**Comment by xginn8** [comment]
@pickmylight can you post the code that you are using? We only recently began supporting InfluxDB 1.7.4, so you should retry with the library built from source.

**Comment by fernandodelacalle** [comment]
same for me, with the example code I get no points  in the dataset. True response. Is the code form the example.

**Comment by fernandodelacalle** [comment]
it is because the new pandas version (0.24.2) with pandas 0.23 everything is ok

**Comment by pickmylight** [comment]
> it is because the new pandas version (0.24.2) with pandas 0.23 everything is ok

thanks, I will try using pandas 0.23

**Comment by pickmylight** [comment]
@xginn8 try using your examplecode for Dataframes. This is the one I'm using

**Comment by xginn8** [comment]
@pickmylight if you install the requirements exactly on the client, do you still see issues writing to a database?

**Comment by siegenthalerroger** [comment]
Can confirm that pandas 0.24 does not work correctly (in my particular case I had datetimes in a non-index row and I received 204s from the server despite nothing being saved)

**Comment by pickmylight** [comment]
@xginn8 I got the requirements on my test system (Raspberry Pi) installed, trying to work things out by testing different Influx and Pandas versions

**Comment by bng85** [comment]
> 
> 
> it is because the new pandas version (0.24.2) with pandas 0.23 everything is ok

Thank you so much for this info. Helped me after almost giving up!
