### ISSUE TITLE
Over UDP points are written to default retention policy instead of given

### ISSUE THREAD

**Issue by anna-arista** [influxdata/influxdb-python#687]
When calling `write_points` on a client over UDP with a given non-default retention_policy, the points are written to the db's default retention_policy; over HTTP, the points are correctly written to the given retention policy for the metric.

**Comment by xginn8** [comment]
@anna-arista I think the retention policy is set at the UDP input level (according to my reading of https://docs.influxdata.com/influxdb/v1.7/supported_protocols/udp#configuration). Can you confirm that is the behavior you are seeing?

**Comment by shantanoo-desai** [comment]
#646 #647 can also address some more information to this query.

**Comment by Manoj321** [comment]
Yes, points all go to "default" retention policy defined in the influxdb.conf. Is this the expected behavior? Is there anyway to send points to a non-default rp with UDP?

**Comment by xginn8** [comment]
@Manoj321 if you configure a second UDP input to apply the RP you desire, you should be able to achieve the desired outcome.

**Comment by Manoj321** [comment]
I see thanks!
