### ISSUE TITLE
create_database support GET

### ISSUE THREAD

**Issue by kingangelAOA** [influxdata/influxdb-python#688]
https://github.com/influxdata/influxdb-python/blob/7d924d5faa5afc0f698297709e95b5d8209a7f52/influxdb/client.py#L578

method POST did not support,  support GET

**Comment by xginn8** [comment]
@kingangelAOA I don't think that is accurate, according to the docs: https://docs.influxdata.com/influxdb/v1.7/guides/writing_data/#creating-a-database-using-the-http-api. Are you having issues with that?

```
To create a database send a POST request to the /query endpoint and set the URL parameter q to CREATE DATABASE <new_database_name>.
```
