### ISSUE TITLE
Support for InfluxDB 2.0

### ISSUE THREAD

**Issue by paritoshjchandran** [influxdata/influxdb-python#695]
So, I'm trying out InfluxDB v2.0 (still in alpha) and was wondering when influxdb-python would support the new version. Is there a timeline? Is there any way I can help contribute?

**Comment by xginn8** [comment]
@paritoshjchandran you can start by running all unit tests against a local instance of InfluxDB v2.0.0. If you run the `test.sh` script with a local copy of the InfluxDB binary in your working directory, you should be able to get an idea for all the changes that may be required. We will not support it officially until it is fully released.

**Comment by paritoshjchandran** [comment]
Sure, let me get down to that... Also, do you have any timeline on when all that's going to happen?

**Comment by xginn8** [comment]
Unfortunately I do not have any special insight into when that will happen. I don't work for the InfluxDB team, I just help maintain this library. You might have better luck reaching out directly on the [slack channel](https://www.influxdata.com/blog/announcing-the-influxdb-slack-channel/)

**Comment by xginn8** [comment]
Closing this issue for now, we will reopen once InfluxDB 2.0 is officially released.

**Comment by franz101** [comment]
@xginn8 what's the status here?
