### ISSUE TITLE
Instant timeout error

### ISSUE THREAD

**Issue by vadi2** [influxdata/influxdb-python#698]
I'm getting an instant fail on write with:

```
InfluxDBServerError: {"error":"timeout"}
```

InfluxDB does not wait before reporting the error. What could be the problem? The firewall is open and influxdb is accessible.

**Comment by xginn8** [comment]
@vadi2 what InfluxDB client and server versions are you using? Can you provide a code snippet that is causing this behavior?

**Comment by vadi2** [comment]
@xginn8 InfluxDB 1.7.5 using the official docker image. I was getting the instant hang using the Python client to just retrieve all known databases, but something is seriously wrong - even using the CLI, `show measures` and `drop database` are just hanging and not responding.

**Comment by xginn8** [comment]
@vadi2 thanks for clarifying that this issue is unrelated to the Python client. While this issue is a little out of scope, have you tried other dockerized versions of the same configuration to rule out a misconfig or any fs corruption issues? You can also open an issue in the respective repository located [here](https://github.com/influxdata/influxdata-docker/issues)

**Comment by vadi2** [comment]
I'll give it a go. Thanks for support here!

**Comment by CarbonUnit** [comment]
@vadi2 Did you find a solution?  I am seeing the same exact timeout failures as you.  
Python 2.7.5
influxdb-python 5.2.2
influxdb 1.7 docker-compose image

**Comment by vadi2** [comment]
That version of Influxdb has a bug, you need to downgrade to 1.6 - or upgrade if they have a fixed release.

**Comment by CarbonUnit** [comment]
Thanks @vadi2 
I tried downgrading to 1.6.  Same problem.  Are you aware of any other work-arounds?  Thanks in advance!

**Comment by vadi2** [comment]
Afraid no.

**Comment by CarbonUnit** [comment]
Thanks.  I ended up just trying forever until success on client side, and restarting docker image on server side.  When it times out.  Hopefully a fix is coming down the pike.  Thanks.
