### ISSUE TITLE
ResultSet.get_points: lack tags in their result set

### ISSUE THREAD

**Issue by timur-orudzhov** [influxdata/influxdb-python#705]
I think, it would be useful that ResultSet.get_points also should return tags related to query. For example, i have query string:

```python
query_string = (
        'SELECT count("some_field") AS "count" '
        'FROM "measurement" '
        'GROUP BY "some_tag", time(1d)'
    )
```

Wright now, after execution this query i will get only *time* and *some_field_count* fields, but i also need info about "some_tag" and its value.

**Comment by clslgrnc** [comment]
What you are looking for is `items`. As per the [documentation](https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#resultset) `get_points` returns "a generator for all the points that match the given filters" this is done by parsing the raw json and should not be significantly faster than:
```python
for (measurement, tags), points in result_set.items():
    if not my_filter(measurement, tags):
        continue
    for point in points:
        do_something(measurement, tags, point)
```

**Comment by aviau** [comment]
This issue looks like a question more than an actual issue. Closing.
