### ISSUE TITLE
Connect to influxdb without port 8086

### ISSUE THREAD

**Issue by mousumipaul** [influxdata/influxdb-python#711]
Hi I am a newbie in python-influxdb. I have used DataFrameClient to create a connection to influxdb from a remote pc. It works with the following sysntax:
client = DataFrameClient(host=ip, username=Influxuser, password=Influxpasswd, database=mydb, ssl=True, verify_ssl=False)

Now for some reason port 8086 has been blocked at the destination PC where influxdb exists. Now I tried with curl command to insert some data from remote pc to influxdb. And it worked. Similarly is it possible to create a connection with influxdb without port 8086 from a remote pc using python-influxdb????

**Comment by aviau** [comment]
Sorry but this isn't a support forum.

Other users may answer, but I won't keep this issue open.
