### ISSUE TITLE
ResultSets Outputs do not provide measurement information for multiple measurement queries

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/influxdb-python#720]
I have two measurements within a database.

I wish to query data from both of the measurements at the same time. For that I use the following query:

    SELECT "v" FROM "wind-angle", "wind-spd" LIMIT 5

This provides me the following result in the InfluxCLI

```
name: wind-angle
time                status type v
----                ------ ---- -
1554798465934000000 0      n2k  173.9
1554798466183000000 0      n2k  359.1
1554798466438000000 0      n2k  336.3
1554798466686000000 0      n2k  127.6
1554798466933000000 0      n2k  12.4

name: wind-spd
time                status type v
----                ------ ---- -
1554798465932000000 0      n2k  1.23
1554798466181000000 0      n2k  0.25
1554798466433000000 0      n2k  0.92
1554798466682000000 0      n2k  1.49
1554798466930000000 0      n2k  1.38
```

However when using the InfluxDB-Client, if I can query the the following (wind-spd first and wind-angle later):

    SELECT "v" FROM "wind-spd","wind-angle" LIMIT 10

I convert the `ResultSet` to `list`

```
    points = db.query(QUERY)
    points = list(points)
    pprint(points)
```
Provides the following output:

```
[[{'time': 1554798465934000000, 'v': 173.9},
  {'time': 1554798466183000000, 'v': 359.1},
  {'time': 1554798466438000000, 'v': 336.3},
  {'time': 1554798466686000000, 'v': 127.6},
  {'time': 1554798466933000000, 'v': 12.4},
  {'time': 1554798467189000000, 'v': 180},
  {'time': 1554798467438000000, 'v': 38.2},
  {'time': 1554798467682000000, 'v': 154.2},
  {'time': 1554798467942000000, 'v': 8.6},
  {'time': 1554798468186000000, 'v': 167.1}],
 [{'time': 1554798465932000000, 'v': 1.23},
  {'time': 1554798466181000000, 'v': 0.25},
  {'time': 1554798466433000000, 'v': 0.92},
  {'time': 1554798466682000000, 'v': 1.49},
  {'time': 1554798466930000000, 'v': 1.38},
  {'time': 1554798467184000000, 'v': 1.08},
  {'time': 1554798467433000000, 'v': 1.08},
  {'time': 1554798467680000000, 'v': 1.28},
  {'time': 1554798467933000000, 'v': 1.33},
  {'time': 1554798468182000000, 'v': 0.77}]]
```

It is worth observing that the first list is actually the value of the `wind-angle` and not `wind-spd`.

Also it is not intuitive as to which sublist belongs to which measurement.

Is there a way to overcome this or perhaps add the measurement name to the list and maintain the order of the measurements ?

**Comment by bapBardas** [comment]
Same issue faced here, I would be interested @shantanoo-desai if you could share the way you did overcome this limitation. 

Thanks !

**Comment by shantanoo-desai** [comment]
@bapBardas Can you have a look at [`get_points` API with `measurement` as a parameter](https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#influxdb.resultset.ResultSet.get_points)

The issue is quite old and I cannot recall it exactly if this issue was actually solved. What generally happens is if you convert the `ResultSet` completely to a list you lose the context.

**Comment by shantanoo-desai** [comment]
@bapBardas Yeah I solved this issue by redesigning my Database Schema. The only way you can get context out is using `get_points(measurement='wind-spd')`  in your code.

```python
from influxdb import InfluxDBClient
from pprint import pprint

client = InfluxDBClient(host='localhost', port=8086, username='root', password='root', database='mydb1')

QUERY = 'SELECT "v" FROM "wind-spd", "wind-angle" LIMIT 10'

result_set = client.query(QUERY)

result_set_spd = result_set.get_points(measurement='wind-spd')
result_set_angle = result_set.get_points(measurement='wind-angle')

pprint(list(result_set_spd))
pprint(list(result_set_angle))

client.close()

```


A better way to this query is to redesign the way you push the data into InfluxDB1.x. I did something like

```
DB: db1
measurement: windcharacteristics
    fields: wind_angle, wind_speed
```

The query you build will be more intuitive like

    SELECT wind_angle from windcharacteristics


But there is no alternative way I could solve this issue
