### ISSUE TITLE
Add support for messagepack 

### ISSUE THREAD

**Issue by lovasoa** [influxdata/influxdb-python#733]
The preferred response format for InfluxDB is now MessagePack, for reasons listed in https://github.com/influxdata/influxdb/issues/8330 .
Supporting it and using it by default when the server supports it too would solve several open issues, such as https://github.com/influxdata/influxdb-python/issues/665  and https://github.com/influxdata/influxdb-python/issues/715. It would also improve performance, and lower the required amount of data to be transmitted between the server and the client.

**Comment by philip-jones** [comment]
I fully support that, but I think JSON vs MessagePack is a completely separate issue to whether the HTTP POST to InfluxDB is gzip'd or not, so perhaps don't conflate the two issues or get sidetracked from implementing gzip support in influxdb-python.

Gzipping will benefit either transfer format.

**Comment by lovasoa** [comment]
To be clear: message pack is used only from the server to the client. gzip is not very useful on msgpack-encoded data since it has a high entropy, but it would definitely help for POST data sent from the client to the server.

**Comment by philip-jones** [comment]
Sorry folks, probably posted my comment on the wrong issue, should have been on https://github.com/influxdata/influxdb-python/issues/718 not this one.

**Comment by http600** [comment]
ya, but how to make server return in `json`
