### ISSUE TITLE
What is the maintenance status of this project ?

### ISSUE THREAD

**Issue by lovasoa** [influxdata/influxdb-python#735]
This project has many opened issues that have never been triaged, many opened pull requests with no comment from the maintainers, and the last commit is three months old. What is the exact status of the project ? Is it still maintained ? Is it supported by InfluxData ? Do you need help for maintaining this project ?

@aviau @xginn8

**Comment by aviau** [comment]
We tend to reply fast if the pull requests contain good tests.

We do this in our free time, this is not supported by influxdata.

I'll close this as we don't keep discussions issues open.

Feel free to contribute if you want to help: Good pull requests with tests.

I have given commit rights to contributord in the past. xginn8 and sebito91 are examples of that. I'll keep doing that as soon as I see someone worthy of it.

**Comment by lovasoa** [comment]
Hello @aviau !
  This is good news ! If you have time, can you review my pull request ? https://github.com/influxdata/influxdb-python/pull/734 
  Maybe, if you are still active on this repository, it would be a good idea to acknowledge it when you receive a new issue or pull request. Maybe you could tell people that you don't have the time to investigate their issue, but indicate a place to look in the code if they want to fix it themselves, and indicate that you accept pull requests. It could help revive the project. Labels could also be added to issues to triage them.
