### ISSUE TITLE
Security fix subversion release 

### ISSUE THREAD

**Issue by Ivo-Donchev** [influxdata/influxdb-python#739]
Hi :)

This security issue fix seems to be really important for existing systems that use it to dynamically building influx queries using `influxdb-python` (with string interpolations)  - https://github.com/influxdata/influxdb-python/pull/678
Would it be possible to release the new version soon ?

Thank you,
Ivo

**Comment by RadoRado** [comment]
Yep, would be great if someone can release this :raised_hands:

**Comment by sebito91** [comment]
Looking into this now...

**Comment by rawkode** [comment]
@sebito91 did we get this tagged on Pypi too?

**Comment by Ivo-Donchev** [comment]
@sebito91 @rawkode I saw that version `5.2.3` has been released in PyPi - https://pypi.org/project/influxdb/ .

Thank you guys for fixing this ticket :slightly_smiling_face: ! I'm closing it
