### ISSUE TITLE
Not possible to import if a certain file is present in $PWD

### ISSUE THREAD

**Issue by weq** [influxdata/influxdb-python#740]
This should be documented if not fixed. I'm unable to load influxdb-python if there is an empty file named "influxdb.py" in the $PWD folder.
I've experienced this issue in both 2.7 and 3.5.3, so I recon it is something do with scoping within the module itself.
It will also fail to import if there is a influxdb.pyc file.

**Comment by aviau** [comment]
This is just how python importing works...

**Comment by aviau** [comment]
https://docs.python.org/3/library/sys.html#sys.path

> the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter
