### ISSUE TITLE
partial write: points beyond retention policy dropped=24

### ISSUE THREAD

**Issue by Shirley-Ji** [influxdata/influxdb-python#748]
I got this error when using write_points. And I didn't change any default retention policy yet.
The json body is this:
```
json_body=[{'measurement': 'data', 'time': '2019-01-01 23:00:00', 'fields': {'a': 3697.0, 'b': 3670.0, 'c': 3697.0, 'd': 44285842, 'e': 3680.5}, 'tags': {'type': '1h', 'basesymbol': 'u', 'symbol': 'abc'}}]
```

My usage:
```
_client = InfluxDBClient(src.utils.const.influxdb["host"],
                         src.utils.const.influxdb["port"],
                         '',
                         '',
                         src.utils.const.influxdb["db"])
_client.create_database(src.utils.const.influxdb["db"])
_client.write_points(json_body)
```

The exception I got:
```
Traceback (most recent call last):
  File "C:/GitLabs/myinfluxtest/src/influxdb/data.py", line 115, in insertdata
    self.client.write_points(json_body)
  File "C:\Program Files\Anaconda3\lib\site-packages\influxdb\client.py", line 490, in write_points
    tags=tags, protocol=protocol)
  File "C:\Program Files\Anaconda3\lib\site-packages\influxdb\client.py", line 551, in _write_points
    protocol=protocol
  File "C:\Program Files\Anaconda3\lib\site-packages\influxdb\client.py", line 327, in write
    headers=headers
  File "C:\Program Files\Anaconda3\lib\site-packages\influxdb\client.py", line 286, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"partial write: points beyond retention policy dropped=24"}
```

**Comment by xginn8** [comment]
Hi @Shirley-Ji, can you let us know what version of InfluxDB you're running to reproduce locally?

**Comment by xginn8** [comment]
After a little more investigation, if you are writing outside the retention policy (i.e., the points would be immediately dropped), InfluxDB now returns this error instead of dropping the points silently. See https://github.com/influxdata/influxdb/pull/8407 for more information. You should be able to change the default RP on the database to include older data.

**Comment by coolvipool** [comment]
I'm too facing similar issue. I have raised a new issue https://github.com/influxdata/influxdb/issues/15307

But no one has been assigned to it. Can you pls help me in assigning it to correct person.

**Comment by Shirley-Ji** [comment]
sorry for late to update.
I found there is an existing RP which blocks the insertion in my influxdb. My issue is resolved after I removed it. Thanks very much @xginn8

**Comment by Doris-233** [comment]
can u tell me how to remove the existing RP to solve the problem? I revised the default RP, but it didn't work.
