### ISSUE TITLE
Raspberry can`t write data to influxdb

### ISSUE THREAD

**Issue by Satforst** [influxdata/influxdb-python#750]
Hello,
I have problem with write data to Influxdb. On Windows python app working fine, but when I try It on raspbian, It show me InfluxDBServerError.
I tried:
`curl -sL -I localhost:8086/ping`
show me error 503.

Also I tried change host to "localhost", "127.0.0.1", "0.0.0.0" without any changes.
In influxdb.conf I have default settings.

InfluxDB is on Raspberry version 9.9
InfluxDB version 1.7.7
influxdb-python version 5.2.2 (the same as on Windows)

Here is my code:
`from influxdb import InfluxDBClient`
`from sys import exc_info`
`from datetime import datetime`

`client = InfluxDBClient(host="10.157.2.215", username="admin", password="pass", port="8086", database="RawData")`
`time_to_json = datetime.now().strftime("%Y-%m-%d %H:%M:%S")`

`json_writer = [ `
`            {`
`                "measurement": "pokus",`
`                "tags": {`
`                    "machine": "machine"`
`                },`
`                    "time": int(time_to_json),`
`                    "fields": {`
`                        "status": "1",`
`                        "run": "5"`
`                    }`
`            }`
`        ]`

`try:`
`    client.write_points(json_writer)`
`except:`
`    print("Writing data to database error: {}".format(exc_info()[0]))`

**Comment by xginn8** [comment]
Hi, if you are having trouble curling the `/ping` endpoint, it seems like your InfluxDB instance is misconfigured and this is not an issue related to the Python library.
