### ISSUE TITLE
docs: readthedocs integration currently broken

### ISSUE THREAD

**Issue by xginn8** [influxdata/influxdb-python#757]
As reported in https://github.com/influxdata/influxdb-python/pull/648, the readthedocs integration seems to have broken again. I am not an admin for this repository, so I am unable to reconfigure the webhook. @aviau, you should be able to reconfigure that here: https://readthedocs.org/dashboard/influxdb-python/integrations/97327/. If that doesn't work, you may have better luck following the instructions here: https://docs.readthedocs.io/en/stable/webhooks.html#github.

Please let me know if I can help!

edit: I've forced a rebuild for now, so the docs should be current at the moment.

**Comment by aviau** [comment]
Should be good to go.
