### ISSUE TITLE
influxdb-python approximates nanoseconds to microseconds when calling write_points in Json format

### ISSUE THREAD

**Issue by rishabh1212** [influxdata/influxdb-python#758]
This is my first time creating the issue. Please forgive for any mistakes
- influxdb-python version: 5.2.3
When points are passed to `write_points` function of `InfluxDBClient` as JSON data, even if we mention time_precision='n', it approximates the time to microseconds. Same does not happen when passed as `line protocol`.

- tested by inserting timestamps `2019-09-24T03:31:00.100000001Z` and `2019-09-24T03:31:00.100000000Z` with one replacing the other

**Comment by sebito91** [comment]
This should all be addressed in recent PRs. Please reopen if you still see an issue.
