### ISSUE TITLE
tags with value 0 or False not pushed to InfluxDB

### ISSUE THREAD

**Issue by michelfripiat** [influxdata/influxdb-python#769]
When I want to push tags with value equaling to 0 or False, the tag is not accepted.
After investigation, the line to blame is here:
https://github.com/influxdata/influxdb-python/blob/3d61f1f465c0fbfbe404c77a4728c5d7268aaf1e/influxdb/_dataframe_client.py#L374

I patched it and here is how I solved it:
Before:
`tag_string = ''.join(
                [",{}={}".format(k, _escape_tag(v)) if v else ''
                 for k, v in sorted(global_tags.items())]
            )`
After:
`tag_string = ''.join(
                [",{}={}".format(k, _escape_tag(v)) if v not in [None, ''] else ''
                 for k, v in sorted(global_tags.items())]
            )`

Furthermore, it would be nice to also send a tags even if the value is None. Here is my proposition:
`tag_string = ''.join(
                [",{}={}".format(k, _escape_tag(v)) if v not in [None, ''] else ",{}={}".format(k, 'None')
                 for k, v in sorted(global_tags.items())]
            )`

**Comment by russorat** [comment]
@michelfripiat thank you for the issue. Is this something you would consider contributing to the project?

**Comment by michelfripiat** [comment]
For sure, what does that imply?

**Comment by russorat** [comment]
@michelfripiat all you need to do is open a pull request with the change you'd identified and someone will take a look.

**Comment by sebito91** [comment]
Closed by #770
