### ISSUE TITLE
Support Flux Language

### ISSUE THREAD

**Issue by probabble** [influxdata/influxdb-python#775]
Reason: My influx instance is 1.7.x and I'd like to execute queries in Flux against it from a Python client.

https://github.com/influxdata/influxdb-python/issues/717

Trying to figure out if there's a plan for this in your lib or why not...

**Comment by aviau** [comment]
The issues section is not a forum, so questions don't fit here.

I renamed your issue, now it makes sense as an issue.

**Comment by sebito91** [comment]
This is not likely to happen within this repo. Though the 1.x branch of influxdb currently supports both flux and influxql as of 1.7.x, we will be making a complete split between 1.x and 2.x at some point in the very near future.

If you want to use a 2.x version of `influxdb` then please look to use our sibling repo: https://github.com/influxdata/influxdb-client-python

If you want to continue to use `influxql` in the 1.x version of `influxdb` then we'll continue to support this here until the system is officially EOL.

Hope that helps!
