### ISSUE TITLE
{"error":"unable to parse ': invalid boolean", missing tag value"}

### ISSUE THREAD

**Issue by krishnacy** [influxdata/influxdb-python#780]
- InfluxDB version:  1.7.7
- Python version: Python 3.7.4
- Operating system version: Windows 10

Hi, 

I'm new to python and I'm trying to write data to influx DB, but I'm getting the either Boolean error or tag missing error. I understand that the comma & spacing is important in using line protocol, somehow I'm unable to get past these error. Kindly support in solving this issue.

Following is my code:
```
import logging
import time
from pymodbus.client.sync import ModbusTcpClient
from pymodbus.constants import Endian
from pymodbus.payload import BinaryPayloadDecoder
from influxdb import InfluxDBClient

client = ModbusTcpClient('localhost', port=502)
iclient = InfluxDBClient(host='localhost', port=8086)
iclient.create_database('writetest')
data_end_time = int(time.time() * 1000)
print(data_end_time)
 if (client.connect()):
     print('connected')
     while 1 :
         request = client.read_holding_registers(0,1)
         value1 = request.registers
         print(value1)
         data_points = ("{measurement},location={location},device={device} x={x} {timestamp}"
                                   .format(measurement='check',
                                           location='Jam',
                                           device='Sen',
                                           x=value1,
                                           timestamp=data_end_time))
         print(data_points)
         iclient.write_points(data_points, database='writetest', time_precision='ms', batch_size=10000, 
 protocol='line')
         time.sleep(1)
 else:
     print('not connected')
```
The error I'm receiving is as follows:

1580715057370
connected
[12]
check,location=Jam,device=Sen x=[12] 1580715057370
Traceback (most recent call last):
  File "C:\Users\Python\Python37-32\pymodfloat.py", line 28, in <module>
    iclient.write_points(data_points, database='writetest', time_precision='ms', batch_size=10000, protocol='line')
  File "C:\Users\Python\Python37-32\pymodfloat.py", line 483, in write_points    tags=tags, protocol=protocol)
  File "C:\Users\Python\Python37-32\pymodfloat.py", line 551, in _write_points    protocol=protocol
  File "C:\Users\Python\Python37-32\pymodfloat.py", line 327, in write    headers=headers
  File "C:\Users\Python\Python37-32\pymodfloat.py", line 286, in request    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"unable to parse 'check,location=Jam,device=Sen  x=[12],1580714373425': invalid boolean"}

1580714343984
connected
[12]
check,location=Jam,device=Sen,x=[12],1580714343984
influxdb.exceptions.InfluxDBClientError: 400: {"error":"unable to parse 'check,location=Zam,device=Sen,x=[12],1580714343984': missing tag value"}

**Comment by russorat** [comment]
@krishnacy thanks for opening this. Looks like the value for `x` is coming through as an array? It would need to be a scaler such as int or float in order to use it as a field.

**Comment by syedriyaz786** [comment]
Repository 'daemonize': Error parsing config: Error parsing "enabled = 'yesi'": invalid boolean value
getting this error while installing java  sudo yum install java-1.8*
