### ISSUE TITLE
Writing Multiple field values

### ISSUE THREAD

**Issue by krishnacy** [influxdata/influxdb-python#789]
Hi there, 

I'm new to influxdb and I'm trying to write multiple fields into influxdb, but it's not working. Kindly support in solving the issue

-InfluxDB version:1.7.7 
-Python version:3.7.4 
- Operating system version:**  Windows 10

the following is my code:

`from influxdb import InfluxDBClient

host = 'localhost'
port = 8086
user = 'root'
password = 'root'
dbname = 'writetest'
myclient = InfluxDBClient(host, port, user, password, dbname)

dat = {"ab": round(raw.decode_32bit_float(),2),
       "bc": round(raw.decode_32bit_float(),2),
       "cd": round(raw.decode_32bit_float(),2)
            }
    print(type(dat))
    print(dat)
    val = {}
    val['measurement']= 'check2'
    val['location'] = 'DEL'
    val['device'] = 'SAT'
    val['fields'] = dat
    print(val)
    myclient.write_points(val)`

the output & error is as follows:
<class 'dict'>
{'pac': 10.1, 'faq': 11.1, 'pdc': 12.1}
{'measurement': 'check2', 'location': 'DEL', 'device': 'SAT', 'fields': {'pac': 10.1, 'faq': 11.1, 'pdc': 12.1}}

File "C:\Users\Python\Python37-32\lib\site-packages\influxdb\line_protocol.py", line 132, in make_lines    point.get('measurement', data.get('measurement'))))
AttributeError: 'str' object has no attribute 'get'

I also tried `val = [{"measurement" : "check1", "tags": {"location": "DEL"},"field":{dat}}]`

but got the following error :

 File "C:\Users\Python\Python37-32\lib\site-packages\influxdb\client.py", line 508, in _batches
    yield iterable[i:i + size] TypeError: unhashable type: 'slice'

Kindly support me in solving this issue

**Comment by shantanoo-desai** [comment]
Place the `location` and `device` in to a key called `tags`:
```
from influxdb import InfluxDBClient

host = 'localhost'
port = 8086
user = 'root'
password = 'root'
dbname = 'writetest'
myclient = InfluxDBClient(host, port, user, password, dbname)

dat = {"ab": round(raw.decode_32bit_float(),2),
"bc": round(raw.decode_32bit_float(),2),
"cd": round(raw.decode_32bit_float(),2)
}
print(type(dat))
print(dat)
val = {}
val['measurement']= 'check2'
val['tags']['location'] = 'DEL'
val['tags']['device'] = 'SAT'
val['fields'] = dat
print(val)
myclient.write_points(val)
```
This should work.

**Comment by krishnacy** [comment]
Hi, 

Thank you for your support.  I tried the following but getting an error

```
val = {}
val['measurement']= 'check2'
val['tags']['location'] = 'DEL'
val['tags']['device'] = 'SAT'
val['fields'] = dat
print(val)
```
error:
<class 'dict'>
{'pac': 10.1, 'faq': 11.1, 'pdc': 12.1}
Traceback (most recent call last):
  File "C:\Users\Python\Python37-32\mod2.py", line 34, in <module>    val['tags']['device'] = 'SAT'
KeyError: 'tags'

Kindly support.

**Comment by shantanoo-desai** [comment]
@krishnacy sorry a mistake from my side.
 It should have the following:
```
val = {'measurement': '', 'tags':{}, 'fields':{}}
```
You should always define the `dict` structure initially. This way you cannot go wrong.

Then go add the your values:

```
val['measurement']= 'check2'
val['tags']['location'] = 'DEL'
val['tags']['device'] = 'SAT'
val['fields'] = dat
```

**Comment by krishnacy** [comment]
@shantanoo-desai : Thank you for your quick support. I'm sorry for the trouble.

Got the same error as before 
"File "C:\Users\Python\Python37-32\lib\site-packages\influxdb\line_protocol.py", line 132, in make_lines point.get('measurement', data.get('measurement'))))
AttributeError: 'str' object has no attribute 'get'"

Kindly support in solving this issue

**Comment by shantanoo-desai** [comment]
you have to send the `val` as an array within `write_points`. Please read the documentation correctly.

```
client.write_points([val])
```

**Comment by krishnacy** [comment]
Thank you. it worked.
