### ISSUE TITLE
Impossible to add time_precision in SeriesHelper / commit

### ISSUE THREAD

**Issue by syndrael** [influxdata/influxdb-python#791]
Hello,
Could you add a new feature to SeriesHelper ?
I can't add time_precision whereas write_points function afford it.

write_points(points, time_precision=None, database=None, retention_policy=None, tags=None, batch_size=None, protocol=u'json', consistency=None)

whereas commit() countains: rtn = client.write_points(cls._json_body_()) (line 146)
I thank you for this new feature.
Kind regards

- **InfluxDB version: 1.7.9
- **InfluxDB-python version: 5.2.3
- **Python version: 3.7.3
- **Operating system version: Debian9

**Comment by russorat** [comment]
@syndrael thanks for opening this. If you're up for it, we'd love to review your PR to fix this issue. Otherwise, we will consider it for a future release.

**Comment by sebito91** [comment]
Fixed in #502 and #719
