### ISSUE TITLE
module 'distutils' has no attribute 'spawn' while running tests

### ISSUE THREAD

**Issue by Hawk777** [influxdata/influxdb-python#798]
- **InfluxDB-python version:** 5.2.3
- **Python version:** 3.6.10
- **Operating system version:** Linux

When I try to run the tests, I get `AttributeError: module 'distutils' has no attribute 'spawn'` in `influxdb_instance.py`. If I change `import distutils` near the top of that file to `import distutils.spawn`, it gets further. Although I admit I don’t really know why `distutils.spawn.find_executable` is even needed, rather than just using `shutil.which`…

**Comment by russorat** [comment]
@Hawk777 thanks for opening this. Would you be willing to submit a PR for the fix?

**Comment by Hawk777** [comment]
Which one? `import distutils.spawn` or switching to `shutil.which`?

**Comment by russorat** [comment]
@Hawk777 tbh, i'm not sure. I'd look to your expertise here to see what makes the most sense. I'll assign this and see if any of the maintainers have a preference.

**Comment by Hawk777** [comment]
I’m no expert. I just tried to run the tests and they fell over. I have no idea why `distutils.spawn.find_executable` exists given that `shutil.which` also exists, but presumably there’s a good reason for it, so I’d rather someone who understand the situation better decide.

**Comment by Hawk777** [comment]
Sigh, Python 2. Looks like influxdb-python cares about it, so that decides the matter. GH-805.

**Comment by russorat** [comment]
Thank you!

**Comment by Hawk777** [comment]
Fixed in GH-805.
