### ISSUE TITLE
test-requirements.txt should include pandas?

### ISSUE THREAD

**Issue by Hawk777** [influxdata/influxdb-python#799]
- **InfluxDB-python version:** 5.2.3
- **Python version:** 3.6.10
- **Operating system version:** Linux

It seems that `pandas` is mentioned in `dev-requirements.txt` but not in `test-requirements.txt`. However, it seems that some of the test suite uses Pandas (`dataframe_client_test.py` in particular). I think it should be in `test-requirements.txt`, shouldn’t it? Thanks!

**Comment by russorat** [comment]
@Hawk777 thanks for this issue as well. Would you be able to open a PR for this one too?

**Comment by Hawk777** [comment]
Seems like adding it to `test-requirements.txt` makes things fall over because it’s already in `tox.ini` which tries to install a different version (or maybe multiple different versions?). I was trying to just run Nose directly when this failed. Thoughts?

**Comment by sebito91** [comment]
The reason we lean on `tox` here is because we're dependent on the version of python for which version of `pandas` and `numpy` to require. It's a bit tougher to do this in the `test-requirements` without specifying the environment in full detail.
