### ISSUE TITLE
beginner trouble 

### ISSUE THREAD

**Issue by khalilmishal** [influxdata/influxdb-python#809]
can someone see what wrong?
<img width="1440" alt="Skjermbilde 2020-04-08 kl  17 50 05" src="https://user-images.githubusercontent.com/63295398/78805408-aa3d1400-79c1-11ea-93a1-d54481f244db.png">

**Comment by shantanoo-desai** [comment]
You should ask such questions at [InfluxDB Community](https://community.influxdata.com/) Issues here are meant for the code repository. 

Also the error suggests that, your python client is unable to connect to the Database. Make sure you are able to reach InfluxDB via your network or if it is on your laptop try a HTTP request via `cURL`:

```bash
curl -i -XGET http://localhost:8086/ping
```
or 

```bash
curl -i -XGET http://IP_Address_of_your_server:8086/ping
```
