### ISSUE TITLE
tags are not stored in database

### ISSUE THREAD

**Issue by aparcar** [influxdata/influxdb-python#821]
- **InfluxDB version:** 1.6.4
- **InfluxDB-python version:** 5.3.0
- **Python version:** 3.8.2
- **Operating system version:** Debian 10

I'm trying to store some tags in the database, however they are missing in the database.

```json
{
    "measurement": "evaluation",
    "tags:": {
        "node": "feather_1",
        "gateway": "feather_gw"
    },
    "time": "2020-04-23 21:38:10.003304+00:00",
    "fields": {
        "temp": 28.6,
        "hum": 67.3,
        "bat": 3.989648,
        "snr": 9.75,
        "cnt": 239,
        "rssi": -37
    }
}
```

Using the influx CLI I tried to check if any tags were stored but the result is empty:
```
> show tag keys
>
```

**Comment by aparcar** [comment]
I found [this](https://influxdb-python.readthedocs.io/en/latest/examples.html#tutorials-serieshelper) example and using the SeriesHelper successfully adds tags.

**Comment by shantanoo-desai** [comment]
@aparcar  if you have resolved this issue please close it

**Comment by aparcar** [comment]
The issue is not resolved, I just found that SeriesHelper do work. However the `client.write_points` function seems broken for `tags`.

**Comment by shantanoo-desai** [comment]
Have you tried passing it into a list:

```python
data = {
    "measurement": "evaluation",
    "tags:": {
        "node": "feather_1",
        "gateway": "feather_gw"
    },
    "time": "2020-04-23 21:38:10.003304+00:00",
    "fields": {
        "temp": 28.6,
        "hum": 67.3,
        "bat": 3.989648,
        "snr": 9.75,
        "cnt": 239,
        "rssi": -37
    }
}

client.write_points([data])
```

**Comment by shantanoo-desai** [comment]
@aparcar Also please not your `data` has a key `"tags:"` and not `"tags"` there is a colon in the keys

**Comment by aparcar** [comment]
Ugh that's it, sorry for wasting your time!
