### ISSUE TITLE
"['model'] not in index" issue ; can't proceed

### ISSUE THREAD

**Issue by priyankadinda22** [influxdata/influxdb-python#824]
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel(r'mtcars.xlsx')

for columns in df:
    plt.figure()
    df.boxplot(columns)

Stuck here with this error.  please guide how to solve it

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-18-930e268fdb5a> in <module>()
      1 for columns in df:
      2     plt.figure()
----> 3     df.boxplot(columns)

~\Anaconda3\lib\site-packages\pandas\plotting\_core.py in boxplot_frame(self, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
   2255     ax = boxplot(self, column=column, by=by, ax=ax, fontsize=fontsize,
   2256                  grid=grid, rot=rot, figsize=figsize, layout=layout,
-> 2257                  return_type=return_type, **kwds)
   2258     plt.draw_if_interactive()
   2259     return ax

~\Anaconda3\lib\site-packages\pandas\plotting\_core.py in boxplot(data, column, by, ax, fontsize, rot, grid, figsize, layout, return_type, **kwds)
   2239             columns = data.columns
   2240         else:
-> 2241             data = data[columns]
   2242 
   2243         result = plot_group(columns, data.values.T, ax)

~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2677         if isinstance(key, (Series, np.ndarray, Index, list)):
   2678             # either boolean or fancy integer index
-> 2679             return self._getitem_array(key)
   2680         elif isinstance(key, DataFrame):
   2681             return self._getitem_frame(key)

~\Anaconda3\lib\site-packages\pandas\core\frame.py in _getitem_array(self, key)
   2721             return self._take(indexer, axis=0)
   2722         else:
-> 2723             indexer = self.loc._convert_to_indexer(key, axis=1)
   2724             return self._take(indexer, axis=1)
   2725 

~\Anaconda3\lib\site-packages\pandas\core\indexing.py in _convert_to_indexer(self, obj, axis, is_setter)
   1325                 if mask.any():
   1326                     raise KeyError('{mask} not in index'
-> 1327                                    .format(mask=objarr[mask]))
   1328 
   1329                 return com._values_from_object(indexer)

KeyError: "['model'] not in index"

**Comment by xginn8** [comment]
Hi, this issue doesn't seem to relate in any way to the influxdb module, so I'm going to close this issue. Please let me know if I've missed something
