### ISSUE TITLE
Context manager for InfluxDBClient not working correctly? 

### ISSUE THREAD

**Issue by stdietrich** [influxdata/influxdb-python#828]
- **InfluxDB version:** 1.8.0
- **InfluxDB-python version:** 5.3.0
- **Python version:** 3.6.8
- **Operating system version:** CentOS 7 x86_64

With #816 support for context managers has been added to InfluxDBClient. I am currently trying to use it, but it seems not to work:
```python
with influxdb.InfluxDBClient(host='host', port=8086, database='db') as client:
    client.write_points(json_body)
```

It fails, as client is `None`:
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    client.write_points(json_body)
AttributeError: 'NoneType' object has no attribute 'write_points'
```

Looking at the source, the `__enter__` function does not return any object, just a pass:
https://github.com/influxdata/influxdb-python/blob/28a30987a9dc2e24dbcf1100d2ae9e48883313bc/influxdb/client.py#L172-L174

Should this not return the client object, e.g.:
```python
 def __enter__(self): 
     """Enter function as used by context manager.""" 
     return self
```

Or am I incorrectly using the context manager with influxdb?

**Comment by russorat** [comment]
@stdietrich thanks for the issue. Could definitely be a bug. Are you comfortable opening a PR to address it?

**Comment by stdietrich** [comment]
Sure, but there is already PR #831, which addresses the problem.

**Comment by antimirov** [comment]
@stdietrich Hi. Could you please check why the CI failed on that single check? I don't have permissions to trigger a re-try.

**Comment by julien10** [comment]
Any news on this issue ?

**Comment by dbrennand** [comment]
Just ran into this issue. Any news on a fix?

**Comment by Ramshield** [comment]
Fix is still pending review: https://github.com/influxdata/influxdb-python/pull/831
