### ISSUE TITLE
ModuleNotFoundError when calling influxdb in ipython

### ISSUE THREAD

**Issue by josesoyo** [influxdata/influxdb-python#839]
Hello,
I am trying to use influxdb in ipython but when I call it, an error message says that the module is not found. Instead, if I try to call it in python, within the same environment, it works perfectly.

![influxdb problem](https://user-images.githubusercontent.com/13557425/88663838-7acf2600-d0dc-11ea-9d9d-308091d1bf28.png)

I have installed influxdb-python using conda-forge. If I try to install influxdb using _pip install influxdb_ I get:

> WARNING: No metadata found in c:\programdata\anaconda3\envs\avint\lib\site-packages
> ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\envs\\avint\\lib\\site-packages\\pytz-2020.1.dist-info\\METADATA'

some extra data:
- Operating system: Windows10
- I can install other packages using pip

**Comment by sakethramanujam** [comment]
The python versions shown in the picture seem to be different, the `ipython` shell shows the `python` version to be `3.7.6` where as your regular `python` environment shows it to be `3.7.7`. May be they're on different environments altogether.

**Comment by josesoyo** [comment]
Yes, I don't know why within the same environment, python and `ipython `have different `python `versions. But they are working in the same environment. 

I think the problem is related with `ipython`, but I was hoping that someone found similar problems.

> The python versions shown in the picture seem to be different, the `ipython` shell shows the `python` version to be `3.7.6` where as your regular `python` environment shows it to be `3.7.7`. May be they're on different environments altogether.

**Comment by josesoyo** [comment]
Thanks 

> The python versions shown in the picture seem to be different, the `ipython` shell shows the `python` version to be `3.7.6` where as your regular `python` environment shows it to be `3.7.7`. May be they're on different environments altogether.

Thanks @sakethramanujam , after checking it more it results you are right. Altough I was activating the environment the ipython and jupyter were from the base envirnment. For this reason it was not working.

I found some related questions in the ipython repository and this was the solution in case someone finds the same problem:
https://github.com/ipython/ipython/issues/10986#issuecomment-418439436

**Comment by sakethramanujam** [comment]
Oh okay! good to know!
Also, thanks for sharing the solution here.
