### ISSUE TITLE
publish latest version to pypi

### ISSUE THREAD

**Issue by TomerCohen95** [influxdata/influxdb-python#861]
Hello,
pull request https://github.com/influxdata/influxdb-python/pull/818 was merged and fixed issue https://github.com/influxdata/influxdb-python/issues/830.

the problem is that it was not published to pypi yet.
can someone upload the latest package? it's causing dependency conflict in our package.
@aviau , @xginn8 , @sebito91

thanks,
Tomer

**Comment by amitwer** [comment]
That would be awesome, I'm dreading the moment pip resolver change will be irreversible and my project will be broken.

**Comment by LiorElb** [comment]
I also need this issue to be fixed for my project, please help.

**Comment by TomerCohen95** [comment]
published, Thanks
