### ISSUE TITLE
Delete API not working

### ISSUE THREAD

**Issue by dilipbm** [influxdata/influxdb-python#865]
- **InfluxDB version:** 2.0.0-rc.3
- **InfluxDB-python version:** 1.9.0
- **Python version:** 3.7.1
- **Operating system version:** macOS 10.13.6

```
token = "TOKEN"
org = "ORG"
bucket = "BUCKET"

client = InfluxDBClient(url=HOST", token=token)

delete_api = client.delete_api()
delete_api.delete(
    "1970-01-01T00:00:00Z",
    "2020-12-01T00:00:00Z",
    '_measurement="conso_elec"',
    bucket=bucket,
    org=org,
)
```

This code throw an `Not implemented` exception. It seems to me that the delete with predicate API `/api/v2/delete` has been disabled in this version of influxdb (https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/)

**Comment by snenkov** [comment]
You are writing in the wrong influx python repo.
It should be here: https://github.com/influxdata/influxdb-client-python
I noticed this today and just figured out that this was indeed a bug which needs fixing: https://github.com/influxdata/influxdb-client-python/issues/168

**Comment by dilipbm** [comment]
Thank you snenkov. Of cours it is not the right one
