### ISSUE TITLE
5.3.1 version is untagged on git/github

### ISSUE THREAD

**Issue by JuniorJPDJ** [influxdata/influxdb-python#917]
Hello.

I spotted 5.3.1 version on pypi and there's no tag like that here.

I'd like to update package on alpine linux repository, but we are using github tarball so I'm unable to do so.

**Comment by JuniorJPDJ** [comment]
bump?

**Comment by jpruciak** [comment]
@rhajek bump

**Comment by bednar** [comment]
Hi All, I will take a look next week.

**Comment by bednar** [comment]
The tag for version 5.3.1 is created: https://github.com/influxdata/influxdb-python/releases/tag/v5.3.1

----
`git tag -a v5.3.1 7b0367309b118e8be97bd85af4433b25129a4618 -m 'chore(CHANGELOG): tagging release to 5.3.1'`
