### ISSUE TITLE
Identify repo owner and move to InfluxCommunity org

### ISSUE THREAD

**Issue by mhall119** [influxdata/influxdb-python#918]
The v1 client libraries for InfluxDB were typically developed and maintained by community members. They have all now been succeeded by v2 client libraries developed and maintained by InfluxData in partnership with Bonitoo.

If there are still users of this v1 client library, and they or somebody else are willing to keep them updated with security fixes at a minimum, this code should be moved to https://github.com/InfluxCommunity and control of it given to the new maintainers. Otherwise let's archive it in favor of the v2 client library.

**Comment by jdstrand** [comment]
This is being archived it in favor of the v2 client library. If there are still users of this v1 client library, and they or somebody else are willing to keep them updated with security fixes at a minimum please reach out on the [Community Forums](https://community.influxdata.com/) or [InfluxData Slack](https://influxdata.com/slack).

cc @Anaisdg
